### ISSUE TITLE
Uncaught exception filling the localhost logs

### ISSUE THREAD

**Issue by med-amine-21** [apereo/cas#1848]
Hi,
While testing my CAS throttling feature. I misconfigured my brute forcer to use GET instead of POST.
To my horror, in the span of half an hour, I got a 6 GB log file containing a single error  (Error 500).
This error is due to sending username or password via GET method which is forbidden by design (RequestParameterPolicyEnforcementFilter).  
I am using CAS 4.0.7. However, even the version 4.2.2 is affected. Here is the link for Apereo's demo of cas (available on their website). 
https://jasigcas.herokuapp.com/cas/login?username=test  

This issue can have serious implications. For example, filling the free space with log until server stops responding whether intentionally or not (misconfiguring the bruteforcer or puposely generating the requests to stop the server) .  
The problem is logged twice once in cas.log which isn't an issue and in localhost.[date].log
 
Here is my Log
```
juin 22, 2016 4:56:30 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: "Servlet.service()" pour la servlet cas a généré une exception
java.lang.RuntimeException: RequestParameterPolicyEnforcementFilter is blocking this request.  Examine the cause in this stack trace to understand why.
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.logExceptionAndThrow(RequestParameterPolicyEnforcementFilter.java:584)
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.github.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: RequestParameterPolicyEnforcementFilter is blocking this request.  Examine the cause in this stack trace to understand why.
	... 27 more
Caused by: java.lang.RuntimeException: username parameter should only be used in POST requests
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.logExceptionAndThrow(RequestParameterPolicyEnforcementFilter.java:584)
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.checkOnlyPostParameters(RequestParameterPolicyEnforcementFilter.java:576)
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:288)
	... 26 more
Caused by: java.lang.IllegalArgumentException: username parameter should only be used in POST requests
	... 28 more
```

**Comment by mmoayyed** [comment]
So turn off/down logging for that package, maybe?

**Comment by med-amine-21** [comment]
Shutting down the logging for cas-server-security didn't resolve the problem. 
I had to disable logging from tomcat. 
Moreover, when browsing the address, you are faced with an error 500 page. 
https://jasigcas.herokuapp.com/cas/login?username=test
I think the best solution is to solve the problem on the code level instead of the logging.

**Comment by mmoayyed** [comment]
Turning off logging for `org.jasig.cas.security` should shut down this error. If it doesn't that is a problem.
How would you want to solve the problem on the code level?

**Comment by med-amine-21** [comment]
Turning off the log in log4j removes the log only from cas.log. 
However the error is logged twice: once cas.log by log4j and once in localhost.[date].log by the jdk.
The cas.log doesn't represent a problem as its size is limited to 1M. On the other hand the localhost file is logged by tomcat and can explode in size (in less than half an hour it became 6Go)
