### ISSUE TITLE
Failed to process @EventListener annotation on bean with name 'servicesManager'

### ISSUE THREAD

**Issue by rkorn86** [apereo/cas#1899]
I have included the following in my report:

- [X] CAS server version: current master as of time of issue submitted (commit 59c4a61ef94a3c2a00323baace8b704af3349682)
- [X] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc): apache-tomcat-8.0.36 running on JVM 1.8.0_92 on Oracle Solaris 11.3 X86
- [x] Steps to duplicate the problem: distribute CAS without default configured service registry (embedded json registry loading services from classpath)
- [x] Stacktraces and CAS logs where appropriate.:
```
org.springframework.beans.factory.BeanInitializationException: Failed to process @EventListener annotation on bean with name 'servicesManager'; nested exception is java.lang.IllegalStateException: Need to invoke method 'handleRefreshEvent' declared on target class 'DefaultServicesManagerImpl', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
        at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:107) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:795) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.jrLockAndRefresh(AbstractApplicationContext.java) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:129) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169) ~[spring-web-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5292) ~[catalina.jar:8.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) ~[catalina.jar:8.0.36]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) ~[catalina.jar:8.0.36]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) ~[catalina.jar:8.0.36]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) ~[catalina.jar:8.0.36]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940) ~[catalina.jar:8.0.36]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816) ~[catalina.jar:8.0.36]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.IllegalStateException: Need to invoke method 'handleRefreshEvent' declared on target class 'DefaultServicesManagerImpl', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.
        at org.springframework.core.MethodIntrospector.selectInvocableMethod(MethodIntrospector.java:136) ~[spring-core-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.aop.support.AopUtils.selectInvocableMethod(AopUtils.java:130) ~[spring-aop-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.context.event.EventListenerMethodProcessor.processBean(EventListenerMethodProcessor.java:156) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        at org.springframework.context.event.EventListenerMethodProcessor.afterSingletonsInstantiated(EventListenerMethodProcessor.java:104) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
        ... 25 more
```

**Comment by mmoayyed** [comment]
When does this happen?

I took out the json service registry, and deployed via the embedded TC container and boot. Logged in, generated an ST, logged out.

How do you exactly duplicate this?

**Comment by rkorn86** [comment]
I've a maven overlay without core modifications, but having `bootstrap.properties` pointing spring cloud config to internal git server providing `cas.properties`, an empty `deployerConfigContext.xml` and some overridden `templates/fragments/*html` with `custom_message.properties`. So nothing special. Ive tested services in services classpath folder and external folder on disk, with the same result. I dont know spring very much, so I cant help very much. I will have a try with embedded TC these days.

**Comment by rkorn86** [comment]
Maybe these warning are related to the issue. They arise just before the error.
```
2016-07-19 08:58:21,682 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanInitializationException: Failed to process @EventListener annotation on bean with name 'servicesManager'; nested exception is java.lang.IllegalStateException: Need to invoke method 'handleRefreshEvent' declared on target class 'DefaultServicesManagerImpl', but not found in any interface(s) of the exposed proxy type. Either pull the method up to an interface or switch to CGLIB proxies by enforcing proxy-target-class mode in your configuration.>
2016-07-19 08:58:21,686 WARN [org.springframework.context.annotation.CommonAnnotationBeanPostProcessor] - <Invocation of destroy method failed on bean with name 'embeddedJsonServiceRegistry': java.lang.NullPointerException>
2016-07-19 08:58:21,688 WARN [org.apereo.cas.services.ServiceRegistryConfigWatcher] - <Directory key is no longer valid. Quitting watcher service>
```

**Comment by mmoayyed** [comment]
Can you share that overlay please?

**Comment by rkorn86** [comment]
There are to much internal company data inside, so sharing is not possible. I could break down the error to a missconfiguration. I've used default `bootstrap.properties` and `application.properties` and disabled loading of `cas.properties` from git and voila CAS is running. Now im going step by step further to my desired config. I will inform you, when i find my config error.

**Comment by mmoayyed** [comment]
Thanks. Closing until we know more.

**Comment by rkorn86** [comment]
It seems, that JRebel caused that Issue. Im using JRebel Remote for faster redeployment of overlay. I will update Jrebel and look deeper into this direction.

**Comment by mmoayyed** [comment]
Sweet. Thanks for reporting back. I use it too, though havent run into that problem; not yet at least :)
