### ISSUE TITLE
Issue configuring CAS 4.2.3 with Mongo service registry

### ISSUE THREAD

**Issue by zimai** [apereo/cas#1914]
After following the CAS 4.2.X documentation for configuring the [Mongo Service Registry](https://apereo.github.io/cas/4.2.x/installation/Mongo-Service-Management.html), the following error is produced in the logs upon deployment from Maven (mvn clean tomcat7:deploy or mvn clean tomcat7:redeploy).

**Usage of 'UserCredentials' with 'MongoClient' is no longer supported**

Root cause appears to be (from tomcat logs):

_Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Usage of 'UserCredentials' with 'MongoClient' is no longer supported. Please use 'MongoCredential' for 'MongoClient' or just 'Mongo'.
	at org.springframework.data.mongodb.core.SimpleMongoDbFactory.<init>(SimpleMongoDbFactory.java:137)
	at org.springframework.data.mongodb.core.SimpleMongoDbFactory.<init>(SimpleMongoDbFactory.java:93)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 120 more_

[tomcatLog.txt](https://github.com/apereo/cas/files/379818/tomcatLog.txt)

Environment:
- OS: Centos 7
- Container: Tomcat 7
- Java 8
- Maven 3.3.9
- Vanilla CAS 4.2.3 Maven Overlay (only customization made is trying to setup Mongo Service Registry)
- Vanilla Mongo DB installed on same server (Centos 7)

Thank you.

**Comment by mmoayyed** [comment]
https://github.com/apereo/cas/issues/1891
