### ISSUE TITLE
SPNEGO Authentication in 4.2.x: CAS produces a 500 error

### ISSUE THREAD

**Issue by samloti** [apereo/cas#1919]
HI,

I try to use CAS apareo on version 4.2.1 with authenticate SPNEGO.
Server rhel 7.2 : tomcat-7.0.54-2, apache  httpd-2.4.6-40 (http to https).

After the configuration ( i use the apareo documentation ) i try to connect on the IE or firefox browser i have this error : 

2016-07-26 16:15:17,984 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-629-kmVhd3sTZCypv01ScNE5-cas.certo.local
2016-07-26 16:15:17,984 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-629-kmVhd3sTZCypv01ScNE5-cas.certo.local
2016-07-26 16:15:17,986 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]
2016-07-26 16:15:17,987 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]
2016-07-26 16:15:17,988 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Mixed-mode authentication is disabled. Executing completion of response
2016-07-26 16:15:17,989 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-630-nfaEyfRgLnFmyaG5lSeQ-cas.certo.local
2016-07-26 16:15:17,989 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-630-nfaEyfRgLnFmyaG5lSeQ-cas.certo.local
2016-07-26 16:15:17,990 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]
2016-07-26 16:15:17,992 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]
2016-07-26 16:15:17,993 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Mixed-mode authentication is disabled. Executing completion of response
2016-07-26 16:15:27,571 DEBUG [org.jasig.cas.web.flow.InitialFlowSetupAction] - Warning cookie path is set to null and path /cas/
2016-07-26 16:15:27,571 DEBUG [org.jasig.cas.web.flow.InitialFlowSetupAction] - Warning cookie path is set to null and path /cas/
2016-07-26 16:15:27,571 DEBUG [org.jasig.cas.web.flow.InitialFlowSetupAction] - TGC cookie path is set to null and path /cas/
2016-07-26 16:15:27,571 DEBUG [org.jasig.cas.web.flow.InitialFlowSetupAction] - TGC cookie path is set to null and path /cas/
2016-07-26 16:15:27,571 DEBUG [org.jasig.cas.web.support.DefaultArgumentExtractor] - No service could be extracted based on the given request
2016-07-26 16:15:27,572 DEBUG [org.jasig.cas.web.support.DefaultArgumentExtractor] - Extractor did not generate service.
2016-07-26 16:15:27,572 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-631-He0aGJg1lklm2QQGPQP3-cas.certo.local
2016-07-26 16:15:27,572 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-631-He0aGJg1lklm2QQGPQP3-cas.certo.local
2016-07-26 16:15:27,572 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]
2016-07-26 16:15:27,572 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]
2016-07-26 16:15:27,573 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Mixed-mode authentication is disabled. Executing completion of response
2016-07-26 16:15:27,573 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-632-gEcwIIJdNVktBwEsWHSa-cas.certo.local
2016-07-26 16:15:27,573 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-632-gEcwIIJdNVktBwEsWHSa-cas.certo.local
2016-07-26 16:15:27,573 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]
2016-07-26 16:15:27,573 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]
2016-07-26 16:15:27,573 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Mixed-mode authentication is disabled. Executing completion of response
2016-07-26 16:15:27,574 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-633-1wZ4XKbv7cYglOK7Rvh9-cas.certo.local
2016-07-26 16:15:27,574 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-633-1wZ4XKbv7cYglOK7Rvh9-cas.certo.local
2016-07-26 16:15:27,574 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]
2016-07-26 16:15:27,574 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]
2016-07-26 16:15:27,575 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Mixed-mode authentication is disabled. Executing completion of response
2016-07-26 16:15:27,575 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-634-Zuw95kKK6NVZcESaHfxn-cas.certo.local
2016-07-26 16:15:27,575 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-634-Zuw95kKK6NVZcESaHfxn-cas.certo.local
2016-07-26 16:15:27,575 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]
2016-07-26 16:15:27,576 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]
2016-07-26 16:15:27,576 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Mixed-mode authentication is disabled. Executing completion of response
2016-07-26 16:15:27,576 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-635-aLbdyvjiH7e2BTYl7YeN-cas.certo.local
2016-07-26 16:15:27,576 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-635-aLbdyvjiH7e2BTYl7YeN-cas.certo.local
2016-07-26 16:15:27,577 DEBUG [org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header [null], User Agent header [Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:MANAGED; GWX:QUALIFIED)]

THanks

**Comment by mmoayyed** [comment]
Where is the error?

**Comment by samloti** [comment]
I use the official documentation  .

This message is not an error : ?
org.jasig.cas.support.spnego.web.flow.SpnegoNegociateCredentialsAction] - Authorization header not found or does not match the message prefix [Negotiate ]. Sending [WWW-Authenticate] header [Negotiate]

when i try to  connect  to my CAS server web (https://cas.../cas/login) i have : 

"response": {
          "status": 500,
          "statusText": "Erreur Interne de Servlet",
          "httpVersion": "HTTP/1.1",
          "headers": [

<h2>CAS is Unavailable</h2>
    <p>There was an error trying to complete your request. <strong>Please notify your support desk or try again.</strong>

**Comment by samloti** [comment]
i modify  this file : WEB-INF/webflow/login/login-webflow.xml 

    <action-state id="generateLoginTicket">
        <evaluate expression="generateLoginTicketAction.generate(flowRequestContext)"/>
        <transition on="generated" to="startSpnegoAuthenticate"/>
    </action-state>

<global-transitions>
        <transition to="startSpnegoAuthenticate" on-exception="org.jasig.cas.services.UnauthorizedSsoServiceException"/>
        <transition to="viewServiceErrorView"
                    on-exception="org.springframework.webflow.execution.repository.NoSuchFlowExecutionException"/>
        <transition to="serviceUnauthorizedCheck" on-exception="org.jasig.cas.services.UnauthorizedServiceException"/>
    </global-transitions>

**Comment by mmoayyed** [comment]
You hadnt pasted in the error in your original log. CAS is sending a 401. You need to figure out what happens afterwards.

**Comment by samloti** [comment]
I understand but,it's been two weeks since I try to understand where does the problem. I try to understand where is the problem. I have not errors on the log.

I'll try to understand, just to mention several people have the same problem as me.

thanks for all

**Comment by dima767** [comment]
Try to look for any errors in `catalina.out` and `localhost<date>.log` files in your Tomcat

**Comment by samloti** [comment]
On the tomcat log 'localhost.2016-07-26.log )  i have : 

Juil. 26, 2016 5:30:33 PM org.apache.catalina.core.StandardHostValve custom
PRÉCIS: Processing ErrorPage[errorCode=500, location=/WEB-INF/view/jsp/errors.jsp]
juil. 26, 2016 5:30:33 PM org.apache.catalina.core.ApplicationDispatcher doForward
PRÉCIS:  Disabling the response for futher output
juil. 26, 2016 5:30:58 PM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [cas] in context with path [/cas] threw exception [Handler processing failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError
        at org.springframework.expression.spel.ast.MethodReference.throwSimpleExceptionIfPossible(MethodReference.java:220)
        at org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:116)
        at org.springframework.expression.spel.ast.MethodReference.access$000(MethodReference.java:49)
        at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:342)
        at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:131)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:299)
        at org.springframework.binding.expression.spel.SpringELExpression.getValue(SpringELExpression.java:84)
        at org.springframework.webflow.action.EvaluateAction.doExecute(EvaluateAction.java:75)
        at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188)
        at org.springframework.webflow.execution.AnnotatedAction.execute(AnnotatedAction.java:145)
        at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51)
        at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:101)
        at org.springframework.webflow.engine.State.enter(State.java:194)
        at org.springframework.webflow.engine.Transition.execute(Transition.java:228)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)
        at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)
        at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)
        at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)
        at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)
        at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)
        at org.springframework.webflow.engine.State.enter(State.java:194)
        at org.springframework.webflow.engine.Transition.execute(Transition.java:228)
        at org.springframework.webflow.engine.DecisionState.doEnter(DecisionState.java:51)
        at org.springframework.webflow.engine.State.enter(State.java:194)
        at org.springframework.webflow.engine.Transition.execute(Transition.java:228)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)
        at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)
        at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)
        at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.handleEvent(FlowExecutionImpl.java:390)
        at org.springframework.webflow.engine.impl.RequestControlContextImpl.handleEvent(RequestControlContextImpl.java:210)
        at org.springframework.webflow.engine.ActionState.doEnter(ActionState.java:105)
        at org.springframework.webflow.engine.State.enter(State.java:194)
        at org.springframework.webflow.engine.Transition.execute(Transition.java:228)
        at org.springframework.webflow.engine.impl.FlowExecutionImpl.execute(FlowExecutionImpl.java:395)
        at org.springframework.webflow.engine.impl.RequestControlContextImpl.execute(RequestControlContextImpl.java:214)
        at org.springframework.webflow.engine.TransitionableState.handleEvent(TransitionableState.java:116)
        at org.springframework.webflow.engine.Flow.handleEvent(Flow.java:547)
"/tmp/titi" 1042L, 94914C

**Comment by samloti** [comment]
if you have any idea because i begin crazy :)

**Comment by dima767** [comment]
Hard to tell.. Would need a good, easy way to reproduce. @mmoayyed - do you know if there is an easy way to set up SPNEGO authn without headache of an external dependencies to debug this?

**Comment by mmoayyed** [comment]
I don't :( I suppose we can once run through the doc and make sure the code is working as expected. Everything else that happens beyond the 401 would be difficult to reproduce without a whole lot of browser setup, and such. Lets keep this open until we know more?

**Comment by lsenecaux** [comment]
I had the same issue if I include cas-server-support-spnego-webflow as a dependency in pom.xml.
I found a workaround :
 A. add cas-server-support-spnego in pom.xml
 B. add action state manually in login webflow before viewLoginForm (see 4.0.x documentation or read source code of cas-server-support-spnego-webflow)

**Comment by mmoayyed** [comment]
What action state is that?

**Comment by lsenecaux** [comment]
startSpnegoAuthenticate

**Comment by lsenecaux** [comment]
@samloti do not forgot to include jaas login file to JAVA_OPTS (see #1909)

**Comment by mmoayyed** [comment]
Great. Could I ask you to submit that change to the CAS docs plz?

**Comment by lsenecaux** [comment]
I will do it

**Comment by samloti** [comment]
Thanks for your help.

My config  summary is : 

on the file pom.xml i add :
 <dependency>
          <groupId>org.jasig.cas</groupId>
          <artifactId>cas-server-support-spnego-webflow</artifactId>
          <version>${cas.version}</version>
   </dependency>

   
   on the file cas-4.2.1/src/main/webapp/WEB-INF/login.conf i add  :
   
   jcifs.spnego.initiate {
   com.sun.security.auth.module.Krb5LoginModule required storeKey=true useKeyTab=true keyTab="/opt/keytab/cas.keytab";
};
jcifs.spnego.accept {
   com.sun.security.auth.module.Krb5LoginModule required storeKey=true useKeyTab=true keyTab="/opt/keytab/cas.keytab";
};

on the file cas-4.2.1/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml i add :

<action-state id="generateLoginTicket">
        <evaluate expression="generateLoginTicketAction.generate(flowRequestContext)"/>
        <transition on="generated" to="startSpnegoAuthenticate"/>
    </action-state>

	 <global-transitions>
        <transition to="startSpnegoAuthenticate" on-exception="org.jasig.cas.services.UnauthorizedSsoServiceException"/>
        <transition to="viewServiceErrorView"
                    on-exception="org.springframework.webflow.execution.repository.NoSuchFlowExecutionException"/>
        <transition to="serviceUnauthorizedCheck" on-exception="org.jasig.cas.services.UnauthorizedServiceException"/>
    </global-transitions>

	
	On the file /etc/cas/cas.properties: i add :
	
	##
# SPNEGO Authentication
#
 cas.spnego.ldap.attribute=spnegoattribute
 cas.spnego.ldap.filter=host={0}
 cas.spnego.ldap.basedn=
 cas.spnego.hostname.pattern=.+
 cas.spnego.ip.pattern=
 cas.spnego.alt.remote.host.attribute
 cas.spengo.use.principal.domain=false
 cas.spnego.ntlm.allowed=true
 cas.spnego.kerb.debug=true
 cas.spnego.kerb.realm=CERTO.LOCAL
 cas.spnego.kerb.kdc=10.10.50.100
 cas.spnego.login.conf.file=/opt/cas-4.2.3/cas-server-webapp/src/main/webapp/WEB-INF/login.conf
 cas.spnego.jcifs.domain=
 cas.spnego.jcifs.domaincontroller=
 cas.spnego.jcifs.netbios.cache.policy:600
 cas.spnego.jcifs.netbios.wins=
 cas.spnego.jcifs.password=
 cas.spnego.jcifs.service.password=
 cas.spnego.jcifs.socket.timeout:300000
 cas.spnego.jcifs.username=
 cas.spnego.kerb.conf=/etc/krb5.conf
 cas.spnego.ntlm=false
 cas.spnego.supportedBrowsers=MSIE,Trident,Firefox,AppleWebKit
 cas.spnego.mixed.mode.authn=false
 cas.spnego.send.401.authn.failure=false
 cas.spnego.principal.resolver.transform=NONE
 cas.spnego.service.principal="HTTP/cas.certo.local@CERTO.LOCAL"

is it correct for you please

**Comment by samloti** [comment]
lsenecaux  i am french :) is it possible you help me please on private for config CAS please .
you can tell me in private : radinota.paul@gmail.com
thanks for all

**Comment by mmoayyed** [comment]
@samloti I may have found the problem. If a patch is produced, are you able to try it and report back its sanity?

**Comment by vosido** [comment]
hi
 i have the same problem and i can test the patch.

Can you tell me please where i can download and install the patch .

thanks for your work

**Comment by mmoayyed** [comment]
Switch your pom overlay version to 4.2.4-SNAPSHOT.

**Comment by mmoayyed** [comment]
Were you able to test?

**Comment by mmoayyed** [comment]
@vosido any updates?

**Comment by Tarrke** [comment]
Hi,

I got the exact same problem (seems to be an infinite loop in the webflow that crash the Java Stack). I tryed to set the pom.xml to fetch the correct version aka 4.2.4-SNAPSHOT but fail to get the proper packages :
`	<properties>
		<cas.version>4.2.4-SNAPSHOT</cas.version>
		<maven-jetty-plugin.version>9.3.6.v20151106</maven-jetty-plugin.version>
		<maven.compiler.source>1.7</maven.compiler.source>
		<maven.compiler.target>1.7</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>`

`[INFO] Building cas-overlay 1.3.4
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.jasig.cas:cas-server-webapp-actions:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-webapp-support:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-webapp:war:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-ldap:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-saml:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-webapp-themes:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-x509-webflow:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-oauth:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-webapp-actions-aup-webflow:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-pac4j-webflow:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-rest:jar:4.2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.jasig.cas:cas-server-support-spnego-webflow:jar:4.2.4-SNAPSHOT is missing, no dependency information available`

I'm interested in helping on this subject if I can.

**Comment by mmoayyed** [comment]
Your repositories section is missing the nexus snapshot repository. Add that and then use -U to force updates.

**Comment by mmoayyed** [comment]
Since 4.2.4 is released, you could also just use that.

**Comment by Tarrke** [comment]
Trying to use the 4.2.4 release ATM

**Comment by mmoayyed** [comment]
Excellent. Thanks for the update!

**Comment by Tarrke** [comment]
No problem if fixing my problem can help others.

**Comment by bplessis** [comment]
I also have experienced a few 500 errors with SPNEGO/CAS 4.2.4 (not tested 4.2.5 but the root cause semm to be still there).

The error was found in the "localhost.<date>" log file of the tomcat servlet engine, something like:
The method getDispatcherType() is undefined for the type HttpServletRequest"

The cause seemed to be that the servlet-api-2.4.jar was embedded in the .war file when adding spnego dependency, apparently due to jcifs package.

A friend helping me with CAS provided the following block for maven dependency:
        <dependency>
            <groupId>org.jasig.cas</groupId>
            <artifactId>cas-server-support-spnego</artifactId>
            <version>${cas.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

 And this fixed the issue.
