### ISSUE TITLE
Setting spring.cloud.bus.enabled to false leads to NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by rkorn86** [apereo/cas#1929]
I have included the following in my report:

- [x] CAS server version: `a83e543d74ce023e3c6dc28cf037fa86917f6a34`
- [x] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc): Integrated Tomcat
- [x] Steps to duplicate the problem: uncomment `spring.cloud.bus.enabled=false` in `cas-server-webapp/src/main/resources/bootstrap.properties` and run via `./gradlew :cas-server-webapp:bootRun`
- [x] Stacktraces and CAS logs where appropriate.
```
2016-07-29 13:29:33,929 INFO [org.apereo.cas.web.CasWebApplication] - <The following profiles are active: default>
2016-07-29 13:29:39,087 INFO [org.apache.catalina.core.StandardService] - <Starting service Tomcat>
2016-07-29 13:29:39,090 INFO [org.apache.catalina.core.StandardEngine] - <Starting Servlet Engine: Apache Tomcat/8.5.4>
2016-07-29 13:29:39,379 INFO [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/cas]] - <Initializing Spring embedded WebApplicationContext>
2016-07-29 13:29:39,639 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 0 services from InMemoryServiceRegistryDaoImpl.>
2016-07-29 13:29:42,145 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dashboardController': Unsatisfied dependency expressed through field 'busProperties': No qualifying bean of type [org.springframework.cloud.bus.BusProperties] found for dependency [org.springframework.cloud.bus.BusProperties]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.bus.BusProperties] found for dependency [org.springframework.cloud.bus.BusProperties]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}>
2016-07-29 13:29:42,149 INFO [org.apache.catalina.core.StandardService] - <Stopping service Tomcat>
2016-07-29 13:29:42,212 restartedMain ERROR Unable to rename cas.log to cas-2016-07-29-13-1.log due to NoSuchFileException - cas.log
2016-07-29 13:29:42,213 restartedMain ERROR Unable to rename file /home/setti/.eclipse/workspaces/cas-upstream/cas-server/cas.log to /home/setti/.eclipse/workspaces/cas-upstream/cas-server/cas-2016-07-29-13-1.log due to NoSuchFileException - cas.log
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dashboardController': Unsatisfied dependency expressed through field 'busProperties': No qualifying bean of type [org.springframework.cloud.bus.BusProperties] found for dependency [org.springframework.cloud.bus.BusProperties]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.bus.BusProperties] found for dependency [org.springframework.cloud.bus.BusProperties]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:775)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:313)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.apereo.cas.web.CasWebApplication.main(CasWebApplication.java:61)
        ... 5 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.bus.BusProperties] found for dependency [org.springframework.cloud.bus.BusProperties]: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1403)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1056)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1018)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
        ... 23 more
:lintGradle

BUILD SUCCESSFUL

Total time: 27.654 secs
```
- [x] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/: see above

**Comment by rkorn86** [comment]
Maybe related to some usage of the `@ConditionalOnBusEnabled` annotation?

**Comment by mmoayyed** [comment]
Try the new snapshot. 

Also try not to modify bootstrap.properties where and when you can.
