### ISSUE TITLE
TokenAuthenticationHandler: authenticator cannot be null

### ISSUE THREAD

**Issue by leleuj** [apereo/cas#2000]
When adding the  `cas-server-support-token-webflow` dependency and trying to authenticate via a JWT token (example: `http://localhost:8888/cas/login?service=http://token&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqZWF3aW4iLCJleHAiOjE0NzEzMzQ1NTUsImlkIjoxfQ.8lAqn6RPdX7-B8PR0QTUnlZRWhSnq-UBpklev0IlfaU`), I get the following error:

```
2016-09-15 14:47:09,586 WARN [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <Service [^https?://.*] does not define a property [jwtSigningSecret] in the registry>
2016-09-15 14:47:09,587 WARN [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <Service [^https?://.*] does not define a property [jwtEncryptionSecret] in the registry>
2016-09-15 14:47:09,589 WARN [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <No token signing secret is defined for service [^https?://.*]. Ensure [jwtSigningSecret] property is defined for service>
2016-09-15 14:47:09,591 ERROR [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <Failed to validate credentials>
org.pac4j.core.exception.TechnicalException: authenticator cannot be null
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:131) ~[pac4j-core-1.9.1.jar!/:?]
	at org.pac4j.core.util.CommonHelper.assertNotNull(CommonHelper.java:152) ~[pac4j-core-1.9.1.jar!/:?]
	at org.apereo.cas.integration.pac4j.authentication.handler.support.AbstractWrapperAuthenticationHandler.doAuthentication(AbstractWrapperAuthenticationHandler.java:62) ~[cas-server-support-pac4j-authentication-5.0.0.RC2-SNAPSHOT.jar!/:5.0.0.RC2-SNAPSHOT]
	at org.apereo.cas.authentication.handler.support.AbstractPreAndPostProcessingAuthenticationHandler.authenticate(AbstractPreAndPostProcessingAuthenticationHandler.java:59) ~[cas-server-core-authentication-5.0.0.RC2-SNAPSHOT.jar!/:5.0.0.RC2-SNAPSHOT]
	at org.apereo.cas.authentication.AbstractAuthenticationManager.authenticateAndResolvePrincipal(AbstractAuthenticationManager.java:210) ~[cas-server-core-authentication-5.0.0.RC2-SNAPSHOT.jar!/:5.0.0.RC2-SNAPSHOT]
	at org.apereo.cas.authentication.PolicyBasedAuthenticationManager.lambda$null$2(PolicyBasedAuthenticationManager.java:102) ~[cas-server-core-authentication-5.0.0.RC2-SNAPSHOT.jar!/:5.0.0.RC2-SNAPSHOT]
```

It seems there is some default configuration issue.

**Comment by mmoayyed** [comment]
May be obvious, but you sure you provided a service defn that contains JWTs?

**Comment by leleuj** [comment]
Yes, I think so. Here is the demo I use: https://github.com/pac4j/casserverpac4j

And the service configured for JWT: https://github.com/pac4j/casserverpac4j/blob/master/src/main/resources/services/token-3000.json

And the URL to test: `http://localhost:8888/cas/login?service=http://token&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqZWF3aW4iLCJleHAiOjE0NzEzMzQ1NTUsImlkIjoxfQ.8lAqn6RPdX7-B8PR0QTUnlZRWhSnq-UBpklev0IlfaU`

The JWT is valid as it works with CAS server 4.2.

**Comment by mmoayyed** [comment]
I duplicated your setup, and was unable to duplicate this error on RC2. The JWT is successfully verified, yet pac4j fails to create a profile because the JWT has no sub. 

```
Caused by: org.pac4j.core.exception.TechnicalException: Cannot get claimSet
        at org.pac4j.jwt.credentials.authenticator.JwtAuthenticator.validate(JwtAuthenticator.java:158) ~[pac4j-jwt-1.9.1.jar:?]
        ... 173 more
Caused by: java.lang.NullPointerException
        at org.pac4j.jwt.credentials.authenticator.JwtAuthenticator.createJwtProfile(JwtAuthenticator.java:171) ~[pac4j-jwt-1.9.1.jar:?]
        at org.pac4j.jwt.credentials.authenticator.JwtAuthenticator.validate(JwtAuthenticator.java:156) ~[pac4j-jwt-1.9.1.jar:?]
        ... 173 more
```

JWT:

```
{"iss":"jeawin","id":1,"exp":1471334555}
```

pac4j has been updated since 4.2 It's possible checks are correctly stopping you for authenticating. It would however be useful for pac4j to not NPE, and report what is actually required from JWT, aka sub, etc.

**Comment by leleuj** [comment]
Did you successfully run my demo? Could it be related to another dependency?

I just opened: https://github.com/pac4j/pac4j/issues/674 to track the NPE issue.

**Comment by mmoayyed** [comment]
Not your demo, I ran a quick test against master and that checked out. So yes I am inclined to the blame the demo :) It's possible JWT dependencies are different. I'll run through that as well and report back.

**Comment by leleuj** [comment]
Did you finally test it with my demo?

**Comment by mmoayyed** [comment]
Not yet, thanks for the reminder. I'll try it shortly.

**Comment by mmoayyed** [comment]
Ran the demo. Discovered a few issues wrt of encryption config and JCE, but nothing close to the original error report here.

**Comment by mmoayyed** [comment]
We'll need to make sure the token authn is able to set up pac4j's authenticator correctly, given signing/encryption config has changed.

**Comment by mmoayyed** [comment]
Also we should account for that the fact that token-authn may go through MFA as well.

**Comment by leleuj** [comment]
Strange you cannot reproduce the issue.

I just ran: `mvn clean package; java -Xmx256m -Dcas.port=8888 -Dcas.path=/cas -Dcas.server.prefix=http://localhost:8888/cas -jar target/cas.war`, called `http://localhost:8888/cas/login?service=http://token&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqZWF3aW4iLCJleHAiOjE0NzEzMzQ1NTUsImlkIjoxfQ.8lAqn6RPdX7-B8PR0QTUnlZRWhSnq-UBpklev0IlfaU` and got:

```
2016-09-27 11:53:55,033 WARN [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <No token signing secret is defined for service [^https?://.*]. Ensure [jwtSigningSecret] property is defined for service>
2016-09-27 11:53:55,033 ERROR [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <Failed to validate credentials>
org.pac4j.core.exception.TechnicalException: authenticator cannot be null
	at org.pac4j.core.util.CommonHelper.assertTrue(CommonHelper.java:132) ~[pac4j-core-1.9.2.jar!/:?]
	at org.pac4j.core.util.CommonHelper.assertNotNull(CommonHelper.java:153) ~[pac4j-core-1.9.2.jar!/:?]
```

**Comment by mmoayyed** [comment]
That makes sense. Because: `^https?://.*` is a valid pattern for `http://token` and is matches first. Adjust the evaluation order or change the pattern.

**Comment by mmoayyed** [comment]
So to followup, if I change the evaluation order for the token service to be 999 (one less than the OIDC service), I can successfully pass the validator, but of course get an NPE because the token has no subject.

**Comment by mmoayyed** [comment]
Let me try with 1.9.3

**Comment by mmoayyed** [comment]
And with 1.9.3, I get:

```
2016-09-27 14:34:35,375 ERROR [org.apereo.cas.authentication.handler.support.TokenAuthenticationHandler] - <Failed to validate credentials>
org.pac4j.core.exception.TechnicalException: JWT must contain a subject ('sub' claim)
	at org.pac4j.jwt.credentials.authenticator.JwtAuthenticator.createJwtProfile(JwtAuthenticator.java:200) ~[pac4j-jwt-1.9.3-SNAPSHOT.jar!/:?]
	at org.pac4j.jwt.credentials.authenticator.JwtAuthenticator.validate(JwtAuthenticator.java:188) ~[pac4j-jwt-1.9.3-SNAPSHOT.jar!/:?]
	at org.pac4j.jwt.credentials.authenticator.JwtAuthenticator.validate(JwtAuthenticator.java:40) ~[pac4j-jwt-1.9.3-SNAPSHOT.jar!/:?]
	at org.apereo.cas.integration.pac4j.authentication.handler.support.AbstractWra
```

Which is fine.

**Comment by leleuj** [comment]
You're right. Sorry for the false positive.
