### ISSUE TITLE
CAS SSO stops working after 1hr

### ISSUE THREAD

**Issue by gadepoonam** [apereo/cas#2009]
Recently we have upgraded tomcat from version  7.0.65 to 7.0.70 and we started facing intermittent connectivity issue for SSO with CAS.

We have deployed CAS 4.1.2 on tomcat 7.0.70 for SSO implementation.
CAS application interacts with third party application(TAP) deployed on JBoss EAP 6.1.

We are able to successfully access third party application for around 1-2hrs via SSO.
Post that we are getting access forbidden error. In CAS logs we are able to see error related to memory leak.
If we restart the server after this, still we keep on getting access forbidden error.

When we revert back the tomcat to older version 7.0.65, SSO works consistently.
If we again change the tomcat to version 7.0.70, SSO works intermittently.

Could you guide us for this issue.

**Error in tomcat catalina.out**
SEVERE: The web application [/pspcas] appears to have started a thread named [scheduler_Worker-10] but has failed to stop it. This is very likely to create a memory leak.  

**Error in JBoss log:**
2016-09-16 10:03:37,516 | ERROR | Unknown-principal | 4Yv2EGJeW6MV3mJkKBIh2vZY | /wui/logout | http-/0.0.0.0:5056-9 | c.s.handled-errors | null
java.lang.IllegalStateException: null
        at org.apache.catalina.connector.ResponseFacade.sendRedirect(ResponseFacade.java:420) ~[jbossweb-7.2.2.Final-redhat-1.jar!/:7.2.2.Final-redhat-1]
        at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:170) ~[jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-1.jar!/:1.0.2.Final-redhat-1]

2016-09-16 10:03:37,522 | ERROR | Unknown-principal | 4Yv2EGJeW6MV3mJkKBIh2vZY | /wui/logout | http-/0.0.0.0:5056-9 | c.sitemap         | An exception occured while handling errors at <map:handle-errors> - file:///home/taptech/Temenos/appl/OCS/WQDEV1/current/ocs-instance/deployments/ocs-app.ear/wui.war/sitemap/patched-sitemap.xmap:919:20
java.lang.IllegalStateException: JBWEB000043: Cannot create a session after the response has been committed
        at org.apache.catalina.connector.Request.doGetSession(Request.java:2627) ~[jbossweb-7.2.2.Final-redhat-1.jar!/:7.2.2.Final-redhat-1]

I have included the following in my report:

- [] CAS server version
- [] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [] Steps to duplicate the problem
- [] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by mmoayyed** [comment]
That's really a question for the tomcat folks. I am not aware of what the differences are between those two versions.
