### ISSUE TITLE
Cannot release lock owned by null with CAS 4.2.5 and Memcache

### ISSUE THREAD

**Issue by wallon-ines** [apereo/cas#2017]
Hello,

I have an error with Memcache and CAS 4.2.5. I often have error messages in cas.log

>2016-09-26 16:30:16,813 DEBUG [org.jasig.cas.ticket.registry.JpaTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
 2016-09-26 16:30:16,817 ERROR [org.quartz.core.JobRunShell] - <Job DEFAULT.JpaTicketRegistry8c2e357d-1d68-4e51-af25-93003a495fe2 threw an unhandled Exception: 
java.lang.IllegalStateException: Cannot release lock owned by null
	at org.jasig.cas.ticket.registry.support.JpaLockingStrategy.release(JpaLockingStrategy.java:139)
	at org.jasig.cas.ticket.registry.support.JpaLockingStrategy$$FastClassBySpringCGLIB$$4fb1c5d4.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.jasig.cas.ticket.registry.support.JpaLockingStrategy$$EnhancerBySpringCGLIB$$3ae05ee.release(<generated>)
	at sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy87.release(Unknown Source)
	at org.jasig.cas.ticket.registry.JpaTicketRegistryCleaner.execute(JpaTicketRegistryCleaner.java:86)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
>

Why does it appear ?

Best regards

**Comment by mmoayyed** [comment]
If you are running Memcache, why is there a reference to JPA/Databases in your configuration?

**Comment by wallon-ines** [comment]
Hello,

I have comment jpa "cas-server-support-jpa-ticket-registry" artefact in pom.xml and I have disabled ticketreg.database.* in properties.

And actually I have another erro r:

> 2016-09-27 09:45:04,367 INFO [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <Beginning ticket cleanup...>
2016-09-27 09:45:04,368 DEBUG [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <Cleaning up tickets from an instance of org.jasig.cas.ticket.registry.MemCacheTicketRegistry@484f8818>
2016-09-27 09:45:04,368 DEBUG [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <Cleaning up tickets from an instance of org.jasig.cas.ticket.registry.MemCacheTicketRegistry@484f8818>
2016-09-27 09:45:04,368 ERROR [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <getTickets not supported.
java.lang.UnsupportedOperationException: getTickets not supported.
	at org.jasig.cas.ticket.registry.MemCacheTicketRegistry.getTickets(MemCacheTicketRegistry.java:181)
	at org.jasig.cas.ticket.registry.TicketRegistryCleaner.execute(TicketRegistryCleaner.java:117)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quart

Why does it appear ?

Best regards

**Comment by mmoayyed** [comment]
Because it tries to clean up tickets for you and memcache version of the cleaner does not support that.
