### ISSUE TITLE
mapping attributes to urn does not work for SamlRegisteredService

### ISSUE THREAD

**Issue by ernestojanus** [apereo/cas#2023]
CAS version: 5.0.0.RC3-SNAPSHOT

#### steps to reproduce
- configure according to instructions for SAML2 Auth

https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md

- register metadata at https://www.testshib.org

- register service to allow access to CAS, with attribute mapped to urn
```json
{
  "@class" : "org.apereo.cas.support.saml.services.SamlRegisteredService",
  "serviceId" : "https://sp.testshib.org/shibboleth-sp",
  "name" : "SAMLService",
  "id" : 10000003,
  "evaluationOrder" : 10,
  "metadataLocation" : "http://www.testshib.org/metadata/testshib-providers.xml",
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnMappedAttributeReleasePolicy",
    "allowedAttributes" : {
      "@class" : "java.util.TreeMap",
      "uid" : "uid",
      "displayName" : "urn:mace:dir:attribute-def:displayName"
    }
  }
}
```
- try to login to shibboleth-sp

go to https://sp.testshib.org/ and follow instructions

#### result
HTTP 500 error with cause
<pre>
org.jasig.cas.client.validation.TicketValidationException: No principal was found in the response from the CAS server.
	at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:98) ~[cas-client-core-3.4.1.jar!/:3.4.1]
[..]
</pre>

#### analysis
The attribute name gets converted to CAS-protocol somewhere down the line (specifically: when creating a ticket validation response), which results in a parse-error when it gets read trying to build a SAML response.
 See cas.log (with log level DEBUG for org.jasig)
<pre>
2016-09-28 13:37:16,813 ERROR [org.jasig.cas.client.util.XmlUtils] - <Element type "cas:urn" must be followed by either attribute specifications, ">" or "/>".>
org.xml.sax.SAXParseException: Element type "cas:urn" must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.seekCloseOfStartTag(XMLDocumentFragmentScannerImpl.java:1396) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:248) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[?:1.8.0_91]
	at org.jasig.cas.client.util.XmlUtils.getTextForElement(XmlUtils.java:192) ~[cas-client-core-3.4.1.jar!/:3.4.1]
	at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:81) ~[cas-client-core-3.4.1.jar!/:3.4.1]
	at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:201) ~[cas-client-core-3.4.1.jar!/:3.4.1]
	at org.apereo.cas.support.saml.web.idp.profile.SSOPostProfileCallbackHandlerController.handleCallbackProfileRequest(SSOPostProfileCallbackHandlerController.java:60) ~[cas-server-support-saml-idp-5.0.0.RC3-SNAPSHOT.jar!/:5.0.0.RC3-SNAPSHOT]
[..]
</pre>

The error is due to the colons in the attribute name, as this results in an XML element name with multiple colons: 
```xml
<cas:urn:mace:dir:attribute-def:displayName>Scott Testvictim</cas:urn:mace:dir:attribute-def:displayName>
```

Changing the mapping target name to e.g. urn_mace_dir_attribute-def_displayName will fix the login to the SP, but of course the attribute is then not recognized.

**Comment by mmoayyed** [comment]
I wonder if this is something we should accommodate at the client level rather than here, but either way, it needs to be addressed.
