### ISSUE TITLE
[MFA][GAUTH] - Reusing OTP must be forbidden

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#2041]
### Issue
cas version : 5.0 RC4

I had configured a service to use MFA (through google auth).
I log me in with my credentials, I provide my OTP (123456), and I am redirected to the service.
I log me out from CAS, and then I reconnect to the service again.
I enter my crendentials, I provide the same OTP as above (123456), and my connection is accepted ! :-(
It is not the purpose of OTP !

Overlay https://github.com/cas-projects/cas-issues/pull/20

**Comment by lsenecaux** [comment]
I suggest that, like in pam authentication for unix, the system retains the timestamps of OTP that were previously used

**Comment by mmoayyed** [comment]
Could you attach logs at DEBUG level?

**Comment by lsenecaux** [comment]
Here my logs

[logs.zip](https://github.com/apereo/cas/files/528783/logs.zip)

**Comment by mmoayyed** [comment]
Had a look. Seems like a problem, yes. Before I step into this, what's this?

```
2016-10-14 08:06:57,469 DEBUG [org.apereo.cas.authentication.FileTrustStoreSslSocketFactory] - <Enabled protocols: [TLSv1, TLSv1.1, TLSv1.2]>
2016-10-14 08:06:57,469 DEBUG [org.apereo.cas.authentication.FileTrustStoreSslSocketFactory] - <Enabled cipher suites:[TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]>
2016-10-14 08:06:57,469 DEBUG [org.apereo.cas.authentication.FileTrustStoreSslSocketFactory] - <Starting handshake>
2016-10-14 08:06:57,534 DEBUG [org.apereo.cas.authentication.FileTrustStoreSslSocketFactory$CompositeX509TrustManager] - <Certificate chaining error>
sun.security.validator.ValidatorException: Certificate chaining error
	at sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:204) ~[?:1.8.0_102]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_102]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_102]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_102]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105) ~[?:1.8.0_102]
	at org.apereo.cas.authentication.FileTrustStoreSslSocketFactory$CompositeX509TrustManager.lambda$checkServerTrusted$1(FileTrustStoreSslSocketFactory.java:236) ~[cas-server-core-authentication-5.0.0.RC4-SNAPSHOT.jar:5.0.0.RC4-SNAPSHOT]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_102]

```

**Comment by mmoayyed** [comment]
I also recommend you turn up logs for `com.warrenstrange.googleauth` and see that produce an explanation for this behavior.

**Comment by lsenecaux** [comment]
`com.warrenstrange.googleauth` is already at debug level to cas.log

**Comment by mmoayyed** [comment]
Strange. Dont see any log statements in the logs.

Have you tried debugging the issue by stepping int the authentication handler and see how it might accept duplicate codes?

**Comment by lsenecaux** [comment]
I think the `Certificate chaining error` is due to I access an SSL service with a valid cert, however my cas server v5 has a self signed cert

**Comment by lsenecaux** [comment]
I had this 
`<AsyncLogger name="com" level="debug" additivity="false" includeLocation="true">
            <AppenderRef ref="casConsole"/>
            <AppenderRef ref="casFile"/>
        </AsyncLogger>` to my log4j2.xml file and in fact I don't see any log  refer to `com.warrenstrange.googleauth`

**Comment by lsenecaux** [comment]
> Have you tried debugging the issue by stepping int the authentication handler and see how it might accept duplicate codes?

How I can do that ?

**Comment by mmoayyed** [comment]
Let me clarify something: Google does not provide you with OTPs. They provide you with Time-based tokens. As long the token is used within the time-window is valid and has not expired, it's considered valid. It's not one-time use.
Also in you configuration, you skewed the window size by `cas.authn.mfa.gauth.windowSize=28800`. So of course, when you mess with the time window for every token, you can reuse and reuse and reuse. 

So fix that and try again.

**Comment by mmoayyed** [comment]
If you actually wish for CAS to support OTPs, that would not be a problem. We might already do via RADIUS.

**Comment by mmoayyed** [comment]
Also study: https://github.com/wstrange/GoogleAuth

> Since TOTP passwords are time-based, it is essential that the clock of both the server and the client are synchronised within the tolerance used by the library. The tolerance is set by default to a window of size 3 and can be overridden when configuring a GoogleAuthenticator instance.

**Comment by lsenecaux** [comment]
I thought the googleauth handler works like the PAM googleauthenticator (https://github.com/google/google-authenticator).
I had put the windowSize to 28800 because with the default value (3), my TOTP was not accepted

**Comment by mmoayyed** [comment]
Gotcha. Right, we use a java binding that is provided in that link above. Using PAM as an alternative or a replacement might not be a bad idea.

You obviously went too far. Just need to play around with the window size, and make sure times are synced between server and client. I am assuming you're running both on the same machine for testing so that shouldn't be a problem.

**Comment by lsenecaux** [comment]
I don't want use PAM as an alternative, I just thought CAS serveur act as PAM does

**Comment by mmoayyed** [comment]
Cool. Understood, thanks for clarifying.

**Comment by lsenecaux** [comment]
IMHO, I think this implementation can provide a security issue if a token can be reused.
Like I said it before, it would be interesting that in future release / patch, timestamps, that were used to compute TOTP, are saved to database to prevent their  usage

**Comment by mmoayyed** [comment]
Agreed. I should say that when I tried a window size of 1 (lowest value allowed; cannot be 0 and the default is 3), I wasn't able to reuse the code at all (within the window or outside of it). So that might be a partial solution; as you say, keeping track of tokens would 100% solve that problem. 

If you'd like to rename this issue and explain the use case, we can definitely accommodate. (Or open up a separate one; that's better)

**Comment by lsenecaux** [comment]
You can close this one.
I will open a new issue and try to explain it more precisly
