### ISSUE TITLE
Infinispan reflection / log4j error in 5.x upon start

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2062]
Testing with 5.0.0.RC3 and 5.0.0.RC4-SNAPSHOT I can't get the embedded container to start when I've included cas-server-support-infinispan-ticket-registry. Don't need to do anything else other than include it. Throwing it in a Tomcat 7 instance also threw the same error. First output after java -jar target/cas.war is:

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.status.StatusLogger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:91)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:93)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:103)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:42)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:189)
	at org.springframework.boot.builder.SpringApplicationBuilder.createSpringApplication(SpringApplicationBuilder.java:99)
	at org.springframework.boot.builder.SpringApplicationBuilder.<init>(SpringApplicationBuilder.java:87)
	at org.apereo.cas.web.CasWebApplication.main(CasWebApplication.java:59)
	... 8 more

I've gone through and tried cleaning as much out as I could, but I haven't been able to get past this message. I find it confusing as there is only one log4j in the project, and from my understanding of the signature, that method has been there for a very long time. There are two commons-beanutils, and I removed the older one (that is brought in by including infinispan), and that didn't fix it. Bringing in infinispan brings in spring-boot-starter-tomcat and the embedded tomcat libs to WEB-INF/lib, when they already exist in WEB-INF/lib-provided. Stopping them from going into WEB-INF/lib didn't fix the issue.

Just tried removing the extra and older commons-collections, httpcore, and spring-retry without success.

**Comment by mmoayyed** [comment]
Confirmed. Looking into it. Stay tuned.

**Comment by mmoayyed** [comment]
This should be fixed. Try again please and report back with  RC 4.
