### ISSUE TITLE
CAS server 4.1.3 Unavailable at login due to NotSerializableException

### ISSUE THREAD

**Issue by vanlanal** [apereo/cas#2081]
We initialize LOG4J directly in Spring Config classes. It seems that sometimes SubistituteLogger is instantiated at startup

So we got following exception during login flow:

<Oct 21, 2016 9:06:28 AM CEST> <Error> <HTTP> <BEA-101017> <[ServletContext@1485662317[app:eures-cas-server module:eures-cas-server.war path:null spec-version:3.0]] Root cause of ServletException.
org.springframework.webflow.execution.FlowExecutionException: Exception thrown in state 'viewLoginForm' of flow 'login'
at org.springframework.webflow.engine.impl.FlowExecutionImpl.wrap(FlowExecutionImpl.java:573)
at org.springframework.webflow.engine.impl.FlowExecutionImpl.start(FlowExecutionImpl.java:227)
at org.springframework.webflow.executor.FlowExecutorImpl.launchExecution(FlowExecutorImpl.java:140)
at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:238)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
Truncated. see log file for complete stacktrace
Caused By: org.jasig.spring.webflow.plugin.ClientFlowExecutionRepositoryException: Error encoding flow execution
at org.jasig.spring.webflow.plugin.ClientFlowExecutionRepository.getKey(ClientFlowExecutionRepository.java:110)
at org.springframework.webflow.engine.impl.FlowExecutionImpl.assignKey(FlowExecutionImpl.java:419)
at org.springframework.webflow.engine.impl.RequestControlContextImpl.assignFlowExecutionKey(RequestControlContextImpl.java:193)
at org.springframework.webflow.engine.ViewState.doEnter(ViewState.java:170)
at org.springframework.webflow.engine.State.enter(State.java:194)
Truncated. see log file for complete stacktrace
Caused By: java.io.NotSerializableException: org.slf4j.helpers.SubstituteLogger
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178

**The problem is that org.jasig.cas.authentication.principal.AbstractWebApplicationService declares a non-static logger (line 43)**

**Comment by mmoayyed** [comment]
Switch to the latest release and try again please.
