### ISSUE TITLE
5.1.0-SNAPSHOT won't deploy to Tomcat < 8.5

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2119]
When trying to deploy the latest snapshot to Tomcat 8.0.38 the following error occurs:

```
2016-11-14 19:16:05,599 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
cas5.ucd.edu_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in class path resource 
[org/apereo/cas/config/CasEmbeddedContainerConfiguration.class]: Bean instantiation via factory method failed; nested exception is 
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method
 'servletContainer' threw exception; nested exception is java.lang.NoSuchMethodError: 
org.apache.catalina.connector.Connector.addUpgradeProtocol(Lorg/apache/coyote/UpgradeProtocol;)V

```

Only fix I have been able to find is to upgrade to Tomcat 8.5.

Travis

**Comment by mmoayyed** [comment]
Fuller stack trace:

```
Caused by: java.lang.NoClassDefFoundError: org/apache/coyote/UpgradeProtocol
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_112]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_112]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_112]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:613) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:524) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:510) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:570) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:694) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:638) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:607) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1456) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:983) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:320) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanType(BeanTypeRegistry.java:309) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:290) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:184) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:173) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:141) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:114) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-1.4.2.RELEASE.jar:1.4.2.RELEASE]
```

**Comment by mmoayyed** [comment]
This has to do with the bean instantiation of the embedded container, even if/when an external tomcat/jetty/etc instance is used. The embedded container by default enables HTTP2, which is a component only provided in Tomcat 8.5.6 and above. 

Should be solved in the latest snapshot.

**Comment by geekmichael** [comment]
I tried Tomcat 9.0.0.M15, got similar error message:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in class path resource [org/apereo/cas/config/CasEmbeddedContainerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.coyote.AbstractProtocol.setSoTimeout(I)V

**Comment by GiovanniMorelli** [comment]
I tried Apache Tomcat/9.0.0.M17, got the same error message:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in class path resource [org/apereo/cas/config/CasEmbeddedContainerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.coyote.AbstractProtocol.setSoTimeout(I)V

**Comment by sunkid0315** [comment]
I tried Apache Tomcat/9.0.0.M18, got the same error message:
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletContainer' defined in class path resource [org/apereo/cas/config/CasEmbeddedContainerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.context.embedded.EmbeddedServletContainerFactory]: Factory method 'servletContainer' threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.coyote.AbstractProtocol.setSoTimeout(I)V
