### ISSUE TITLE
5.1.0 SNAPSHOT cannot deploy the management webapp

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2125]
Reported by @tsschmidt

> I am getting this error when trying to deploy CAS Management app built from the latest 5.1.0-SNAPSHOT.  I have not been able to track down why.

```
2016-11-15 19:07:32,131 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casCoreTicketsConfiguration': Unsatisfied dependency expressed through field 'logoutManager'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.logout.LogoutManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=logoutManager)}>
cas-mgmt5_1     | 2016-11-15 19:07:32,568 ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] - <
cas-mgmt5_1     | 
cas-mgmt5_1     | ***************************
cas-mgmt5_1     | APPLICATION FAILED TO START
cas-mgmt5_1     | ***************************
cas-mgmt5_1     | 
cas-mgmt5_1     | Description:
cas-mgmt5_1     | 
cas-mgmt5_1     | Field logoutManager in org.apereo.cas.config.CasCoreTicketsConfiguration required a bean of type 'org.apereo.cas.logout.LogoutManager' that could not be found.
cas-mgmt5_1     | 
cas-mgmt5_1     | 
cas-mgmt5_1     | Action:
cas-mgmt5_1     | 
cas-mgmt5_1     | Consider defining a bean of type 'org.apereo.cas.logout.LogoutManager' in your configuration.
cas-mgmt5_1     | >
cas-mgmt5_1     | 15-Nov-2016 19:07:32.570 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
cas-mgmt5_1     |  org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/cas-management]]
cas-mgmt5_1     | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
cas-mgmt5_1     | at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
cas-mgmt5_1     | at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
cas-mgmt5_1     | at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
cas-mgmt5_1     | at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
cas-mgmt5_1     | at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
cas-mgmt5_1     | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
cas-mgmt5_1     | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
cas-mgmt5_1     | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
cas-mgmt5_1     | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
cas-mgmt5_1     | at java.lang.Thread.run(Thread.java:745)
cas-mgmt5_1     | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casCoreTicketsConfiguration': Unsatisfied dependency expressed through field 'logoutManager'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.logout.LogoutManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=logoutManager)}
cas-mgmt5_1     | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
cas-mgmt5_1     | at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
cas-mgmt5_1     | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
cas-mgmt5_1     | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
cas-mgmt5_1     | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
cas-mgmt5_1     | at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
cas-mgmt5_1     | at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
cas-mgmt5_1     | at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
cas-mgmt5_1     | at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
cas-mgmt5_1     | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
cas-mgmt5_1     | at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
cas-mgmt5_1     | at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
cas-mgmt5_1     | at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
cas-mgmt5_1     | at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
cas-mgmt5_1     | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
cas-mgmt5_1     | at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
cas-mgmt5_1     | at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
cas-mgmt5_1     | at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
cas-mgmt5_1     | at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
cas-mgmt5_1     | at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
cas-mgmt5_1     | at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
cas-mgmt5_1     | at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
cas-mgmt5_1     | at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
cas-mgmt5_1     | ... 10 more
cas-mgmt5_1     | Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.logout.LogoutManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=logoutManager)}
cas-mgmt5_1     | at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1466)
cas-mgmt5_1     | at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1097)
cas-mgmt5_1     | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
cas-mgmt5_1     | at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
cas-mgmt5_1     | ... 32 more
cas-mgmt5_1     | 
cas-mgmt5_1     | 15-Nov-2016 19:07:32.575 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive /opt/tomcat/webapps/cas-management.war
cas-mgmt5_1     |  java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/cas-management]]
cas-mgmt5_1     | at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:729)
cas-mgmt5_1     | at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
cas-mgmt5_1     | at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
cas-mgmt5_1     | at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
cas-mgmt5_1     | at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
cas-mgmt5_1     | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
cas-mgmt5_1     | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
cas-mgmt5_1     | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
cas-mgmt5_1     | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
cas-mgmt5_1     | at java.lang.Thread.run(Thread.java:745)
cas-mgmt5_1     | 
```

**Comment by mmoayyed** [comment]
This has to do with the fact that the cas-core ticket module is wrongly pulled into the management app by other transitive dependencies. 
@tsschmidt did report that recent commits to master have solved this issue. 
Closing.
