### ISSUE TITLE
CAS 5.1.0-SNAP SPNEGO Webflow not starting : The literal is required

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#2126]
Environment :
- CAS server version 5.1.0-SNAP
- Apache Tomcat 8.5.8 on Debian Jessie 32 bits
- Maven overlay : SPNEGO + LDAP + Yubikey (with custom registry) + SAML (for SAMLv11 ST validation)

I'm trying to bypass MFA if SPNEGO already occured, so I added this line to my cas.properties
`cas.authn.mfa.yubikey.bypass.authenticationHandlerName=JcifsSpnegoAuthenticationHandler`

During start of application, an exception is raised : 
`java.lang.IllegalArgumentException: The literal is required`

Full log is attached, hoping it's verbose enough !

[catalina.out](https://github.com/apereo/cas/files/595236/spnego-510S.txt)

**Comment by mmoayyed** [comment]
Question: this works without the bypass option?

**Comment by mmoayyed** [comment]
Also your logs show this has nothing to do with spring webflow. You probably are running with bad dependencies:

```
Caused by: java.lang.NoSuchMethodError: org.apereo.cas.services.DefaultMultifactorAuthenticationProviderBypass.<init>(Lorg/apereo/cas/configuration/model/support/mfa/MultifactorAuthenticationProperties$BaseProvider$Bypass;)V
	at org.apereo.cas.config.YubiKeyConfiguration.yubikeyBypassEvaluator(YubiKeyConfiguration.java:171)
	at org.apereo.cas.config.YubiKeyConfiguration$$EnhancerBySpringCGLIB$$22766392.CGLIB$yubikeyBypassEvaluator$9(<generated>)
	at org.apereo.cas.config.YubiKeyConfiguration$$EnhancerBySpringCGLIB$$22766392$$FastClassBySpringCGLIB$$96e77b1f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.apereo.cas.config.YubiKeyConfiguration$$EnhancerBySpringCGLIB$$22766392.yubikeyBypassEvaluator(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 46 more
```

**Comment by mmoayyed** [comment]
If you want, you can post an overlay that attempts to duplicate the problem, but this is really a compilation issue on your end where the right dependency version isnt pulled. Do a force update and try again. Post back if the error persists.

**Comment by pmarasse** [comment]
Unfortunately, I ran in a dependency issue right when I took the log yesterday. This morning, after mvn -U, same issue with logs :
  - [bypass enabled](https://github.com/apereo/cas/files/596954/spnego-2.txt)
  - [bypass disabled](https://github.com/apereo/cas/files/596956/spnego-3.txt)
  - [without spnego](https://github.com/apereo/cas/files/597018/no-spnego.txt)

I did not notice differences between bypass enabled/disabled state. But without spnego, application starts.

**Comment by mmoayyed** [comment]
Cool, thanks. I'll take a pass and see if I can reproduce this.

**Comment by mmoayyed** [comment]
Also, I'd advise against using `JcifsSpnegoAuthenticationHandler` as the handler name. You probably should assign YOUR OWN name, because the handler name may change. I realize there are no options to allow you that, and it may be something we expose as well.

**Comment by mmoayyed** [comment]
Unfortunately I cannot duplicate this based on what I think you have done in your overlay, etc. This may be related to #2127 Try again and see if that fix also solved this issue. otherwise, post an overlay plus your config please.

**Comment by pmarasse** [comment]
I can confirm that this issue has gone with #2217. Thank you.
