### ISSUE TITLE
AS 4.2.7 error when deleting TGT tickets using JpaTicketRegistry (related to bug 1817?) 

### ISSUE THREAD

**Issue by randomuser878** [apereo/cas#2151]
Using Mysql 5.5.x, Java 1.8.111, tomcat 8.5.x
 
   Did overlay deployment of multiple versions to find the delta of failure.
   cas 4.2.4 - deletes TGT tickets without causing an error
   cas 4.2.5,4,2,6,6,2,7, all versions fail with message shown below.
   Failure occurs at: cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java, call entityManager.remove(ticket);

   Looks similar to bug #1817, No EntityManager exception with JpaTicketRegistry, CAS 4.2.2, but not sure.

   Did anyone encounter this issue and/or any other ideas how to proceed. 
   Many thanks.

   From: cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
    /**
     * Removes the ticket.
     *
     * @param ticket the ticket
     * @return true if ticket was removed
     */
    public boolean removeTicket(final Ticket ticket) {
        try {
            if (logger.isDebugEnabled()) {
                final Date creationDate = new Date(ticket.getCreationTime());
                logger.debug("Removing Ticket [{}] created: {}", ticket, creationDate.toString());
             }
            entityManager.remove(ticket);
            return true;
        } catch (final Exception e) {
            logger.error("Error removing {} from registry.", ticket, e);
        }
        return false;
    }

2016-11-23 12:32:28,459 DEBUG [org.jasig.cas.ticket.registry.JpaTicketRegistry] - <Removing Ticket [TGT-**********************************************z7yiDDpiXv] created: Wed Nov 23 09:17:52 EST 2016>
2016-11-23 12:32:28,459 ERROR [org.jasig.cas.ticket.registry.JpaTicketRegistry] - <Error removing TGT-**********************************************z7yiDDpiXv from registry.>
javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:278) ~[spring-orm-4.2.8.RELEASE.jar:4.2.8.RELEASE]
        at com.sun.proxy.$Proxy75.remove(Unknown Source) ~[?:?]
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.removeTicket(JpaTicketRegistry.java:89) ~[cas-server-support-jpa-ticket-registry-4.2.7.jar:4.2.7]
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicketsFromResultList(JpaTicketRegistry.java:211) ~[cas-server-support-jpa-ticket-registry-4.2.7.jar:4.2.7]
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteTicketGrantingTickets(JpaTicketRegistry.java:241) ~[cas-server-support-jpa-ticket-registry-4.2.7.jar:4.2.7]
        at org.jasig.cas.ticket.registry.JpaTicketRegistry.deleteSingleTicket(JpaTicketRegistry.java:167) ~[cas-server-support-jpa-ticket-registry-4.2.7.jar:4.2.7]
        at org.jasig.cas.ticket.registry.AbstractTicketRegistry.deleteTicket(AbstractTicketRegistry.java:98) ~[cas-server-core-tickets-4.2.7.jar:4.2.7]
        at org.jasig.cas.ticket.registry.AbstractTicketRegistry$$FastClassBySpringCGLIB$$b70f3271.invoke(<generated>) ~[cas-server-core-tickets-4.2.7.jar:4.2.7]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.2.8.RELEASE.jar:4.2.8.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:651) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
        at org.jasig.cas.ticket.registry.JpaTicketRegistry$$EnhancerBySpringCGLIB$$b42f1b05.deleteTicket(<generated>) ~[cas-server-support-jpa-ticket-registry-4.2.7.jar:4.2.7]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
        at com.sun.proxy.$Proxy86.deleteTicket(Unknown Source) ~[?:?]
        at org.jasig.cas.ticket.registry.TicketRegistryCleaner$1.apply(TicketRegistryCleaner.java:126) ~[cas-server-core-tickets-4.2.7.jar:4.2.7]
        at org.jasig.cas.ticket.registry.TicketRegistryCleaner$1.apply(TicketRegistryCleaner.java:1) ~[cas-server-core-tickets-4.2.7.jar:4.2.7]
        at com.google.common.collect.Iterators$8.transform(Iterators.java:799) ~[guava-18.0.jar:?]
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-18.0.jar:?]
        at org.jasig.cas.ticket.registry.TicketRegistryCleaner.execute(TicketRegistryCleaner.java:139) ~[cas-server-core-tickets-4.2.7.jar:4.2.7]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.2.1.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.2.1.jar:?]
2016-11-23 12:32:28,460 INFO [org.jasig.cas.ticket.registry.TicketRegistryCleaner] - <0 expired tickets found and removed.>
2016-11-23 12:33:20,851 DEBUG [org.jasig.cas.util.CasSpringBeanJobFactory] - <Created job org.jasig.cas.services.DefaultServicesManagerImpl$ServiceRegistry

**Comment by mmoayyed** [comment]
Do you have an overlay you can share?

**Comment by randomuser878** [comment]
Thanks for looking into it.

I created pull request for cas-issue-2151.
Hope I got it right.

Thanks.

**Comment by mmoayyed** [comment]
Thanks. Got your pull.

So what you want to do is, remove everything else from your overlay/PR except the changes that deal with the JPA ticket registry. Update your PR as such. All other custom/inspektr etc changes must be removed. If the problem can be duplicated based on a bare-bones overlay and based on what the docs describe, then we can review it. Otherwise, it's something else you did which would then trigger this issue's closure.

**Comment by randomuser878** [comment]
Greetings
  After cleanup was able to reproduce this issue consistently. 
 Removed everything from overlay besides JPA ticket registry related entries with these two values.
tgt.maxTimeToLiveInSeconds=300
tgt.timeToKillInSeconds=150

Updated overlay for cas-issue-2151

Many thanks.

**Comment by mmoayyed** [comment]
PR: https://github.com/cas-projects/cas-issues/pull/26

**Comment by mmoayyed** [comment]
The only commit I found that might be related here, that is on 4.2.5+ is this: https://github.com/apereo/cas/pull/1982/files

But I was nonetheless unable to duplicate the issue with the latest mysql client and the mysql dialect. Didnt look further into it. If you dig deeper and diagnose this, please post back.

**Comment by randomuser878** [comment]
Greetings

  I tried every permutation of dialect and latest MySQL 5.1.40 jdbc driver. Note it fails also for ST ticket cleanups.  It works per cas 4.2.4, the code refactoring broke something when scheduler runs.
  This is what I did do and get it to work but there are side-effects that make it unusable as a solution. If it provides any clue, any feedback is greatly appreciated.
  Modified:  cas-server-support-jpa-ticket-registry/src/main/java/org/jasig/cas/ticket/registry/JpaTicketRegistry.java
  ...
 +  import javax.persistence.PersistenceContextType;
 ...
- @PersistenceContext(unitName = "ticketEntityManagerFactory")
+ @PersistenceContext(unitName = "ticketEntityManagerFactory", type=PersistenceContextType.EXTENDED)
  private EntityManager entityManager;
  ...

  Besides not being thread safe, it pretty much renders application non-recoverable on database restart. So it is not a solution I can apply. If this gives you some clue perhaps of anything I might be missing, great. 

  Many thanks for looking into this.

**Comment by randomuser878** [comment]
Whoever hits the same issue, this worked for me.
 1)  Copy cas-server-core-tickets/src/main/java/org/jasig/cas/ticket/registry/AbstractTicketRegistry.java
            Methods: deleteTicket and deleteChildren into JpaTicketRegistry.java. No changes to the implementation of these two methods.
2) Hit another issue where the locking of the transaction to the db would not clear. For this changed JpaLockingStrategy.java from Transactional readonly=true to readonly=false.

**Comment by gskjold** [comment]
I can confirm the problem that @randomuser878 describes. I added the following code to org.jasig.cas.ticket.registry.JpaTicketRegistry:

`
    @Override public int deleteTicket(String ticketId) {
        return super.deleteTicket(ticketId);
    }

    @Override public int deleteChildren(TicketGrantingTicket ticket) {
        return super.deleteChildren(ticket);
    }
`

The reason that this works is because the methods now get wrapped by the @Transactional annotation set on the JpaTicketRegistry class, as suggested by the stacktrace where it enters AbstractTicketRegistry on this method which does not have the annotation.

I did not have the locking problem @randomuser878 describes in the previous post.

**Comment by gskjold** [comment]
@mmoayyed Any chance a fix for this will be included in 4.2.8 ? You should be able to replicate the problem by having tickets due for deletion in the database.

**Comment by mmoayyed** [comment]
Sure. If you can demonstrate the problem in a manner that be repeatedly reproduced, by all means. Post an overlay to the issues project that recreates the issue.

Also see:
https://apereo.github.io/cas/developer/Maintenance-Policy.html

**Comment by gskjold** [comment]
Thanks for the info. Planning to bump to 5.0.x in the future, but don't have enough time allocated for it yet.

Not sure how you wanted the overlay delivered, so I just checked it in here:
https://github.com/gskjold/cas-issue-2151

Start, log in as casuser/Mellon and wait up to 90 sec.

**Comment by gskjold** [comment]
@mmoayyed not sure if you have notifications on this, so just a nudge for the previous post with the test case.
