### ISSUE TITLE
CAS - ehcache replication not working with "Unable to correctly extract the Initialization Vector or ciphertext."

### ISSUE THREAD

**Issue by venkatsesharaju** [apereo/cas#2154]
I have included the following in my report:

- [] CAS server version      
4.2.1
- [] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
Tomcat 8.5 / Windows 
- [] Steps to duplicate the problem
Deploy cas on two different tomcat instances 
- [] Stacktraces and CAS logs where appropriate.
2016-11-28 23:13:07,915 DEBUG [org.jasig.cas.web.flow.GenerateLoginTicketAction] - Generated login ticket LT-3-lPcl2UuufrlXwELhTR77-cas01
2016-11-28 23:14:53,576 ERROR [org.jasig.cas.util.WebflowCipherExecutor] - Unable to correctly extract the Initialization Vector or ciphertext.
org.apache.shiro.crypto.CryptoException: Unable to correctly extract the Initialization Vector or ciphertext.
	at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:378)
	at org.jasig.cas.util.BinaryCipherExecutor.decode_aroundBody2(BinaryCipherExecutor.java:102)
	at org.jasig.cas.util.BinaryCipherExecutor$AjcClosure3.run(BinaryCipherExecutor.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
	at org.jasig.cas.util.BinaryCipherExecutor.decode(BinaryCipherExecutor.java:96)
	at org.jasig.cas.util.BinaryCipherExecutor.decode(BinaryCipherExecutor.java:1)
	at org.jasig.cas.web.flow.CasWebflowCipherBean.decrypt_aroundBody4(CasWebflowCipherBean.java:44)
	at org.jasig.cas.web.flow.CasWebflowCipherBean$AjcClosure5.run(CasWebflowCipherBean.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at org.jasig.inspektr.aspect.TraceLogAspect.traceMethod(TraceLogAspect.java:44)
	at org.jasig.cas.web.flow.CasWebflowCipherBean.decrypt(CasWebflowCipherBean.java:43)
	at org.jasig.spring.webflow.plugin.EncryptedTranscoder.decode(EncryptedTranscoder.java:105)
	at org.jasig.spring.webflow.plugin.ClientFlowExecutionRepository.getFlowExecution(ClientFlowExecutionRepository.java:90)
	at org.springframework.webflow.executor.FlowExecutorImpl.resumeExecution(FlowExecutorImpl.java:168)
	at org.springframework.webflow.mvc.servlet.FlowHandlerAdapter.handle(FlowHandlerAdapter.java:228)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.jasig.cas.security.ResponseHeadersEnforcementFilter.doFilter(ResponseHeadersEnforcementFilter.java:227)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.jasig.cas.security.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:250)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.jasig.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:193)
	at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:322)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:370)
	... 65 more

- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/
Yes

**Comment by mmoayyed** [comment]
And where exactly is the overlay pushed to in that repo? where is the PR?

**Comment by venkatsesharaju** [comment]
[cas-issue-2154.zip](https://github.com/apereo/cas/files/625482/cas-issue-2154.zip)

Uploaded overlay here

**Comment by venkatsesharaju** [comment]
@mmoayyed  PR - https://github.com/cas-projects/cas-issues/pull/27

**Comment by mmoayyed** [comment]
Why is the PR closed?

**Comment by mmoayyed** [comment]
I ended up downloading your overlay and tried it locally. Could not reproduce the error; was able to successfully login and generate tickets.

**Comment by venkatsesharaju** [comment]
@mmoayyed  - On single node it works fine but when we have it on multiple notes and replication using ehcache RMI.

**Comment by mmoayyed** [comment]
You're going to step into the code very likely and figure out the issue. I am not quite sure this has anything to do with RMI just yet; It looks like something is put into the login webflow that is not quite serializable and that should/would happen either way without or without ehcache perhaps but logs should tell you more, or debug logs.

You probably should also start testing the latest 4.2.x line.

**Comment by venkatsesharaju** [comment]
Have tried the latest version of 4.2.x and i see the same error 

[error.txt](https://github.com/apereo/cas/files/635573/error.txt)

**Comment by mmoayyed** [comment]
The error shows that CAS cannot decrypt the spring webflow state back. This could be a bug somewhere as something apparently is turned into null:

```
Caused by: java.lang.NullPointerException
        at java.lang.System.arraycopy(Native Method) ~[?:1.8.0_66]
        at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:370) ~[shiro-core-1.2.6.jar:1.2.6]
        at org.jasig.cas.util.BinaryCipherExecutor.decode(BinaryCipherExecutor.java:102) ~[
```

Or it could be an issue with your JCA config, etc. The only way to know for sure is to step into the code.

**Comment by venkatsesharaju** [comment]
Got it working.  Its my bad i have missed to configure tgc.encryption.key & tgc.signing.key

**Comment by venkatsesharaju** [comment]
Thanks @mmoayyed for all your help.   Finally i got it working in my environment.
