### ISSUE TITLE
CAS-5.1.0-SNAP issue with proxy callback

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#2201]
Environment :
  - CAS Version: 5.1.0-SNAPSHOT
  - Java Version: 1.8.0_111
  - Container Version: Apache Tomcat/8.5.8
  - Debian 8 (Jessie) 32 bits.
  - phpCAS 1.3.4 client library

When I try to use proxy, callback is done with wrong parameter : pgt instead of pgtId, so callback is not handled properly by phpCAS client. If I change code of phpCAS client (pgtId => pgt), authentication works.

I think, I've found the culprit : org.apereo.cas.ticket.proxy.support.Cas20ProxyHandler (from cas-server-core-tickets), especially handle methods which references CasProtocolConstants.PARAMETER_PROXY_GRANTINOG_TICKET (typo included ^^)

The constant is defined as :
```java
    /** Constant representing the pgt parameter in the request. */
    String PARAMETER_PROXY_GRANTINOG_TICKET = "pgt";
```

Additionally, I've ran into an exception on cas2ProxyFailureView rendering :

```
2016-12-13 14:34:21,375 ERROR [org.springframework.boot.web.support.ErrorPageFilter] - <Forwarding to error page from request [/proxy] due to exception [Error creating bean with name 'cas2ProxyFailureView' defined in BeanDefinition def
ined in class path resource [org/apereo/cas/web/config/CasProtocolViewsConfiguration.class]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'targetBeanName' o
f bean class [org.thymeleaf.spring4.view.ThymeleafView]: Bean property 'targetBeanName' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?]>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cas2ProxyFailureView' defined in BeanDefinition defined in class path resource [org/apereo/cas/web/config/CasProtocolViewsConfiguration.class]: Err
or setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'targetBeanName' of bean class [org.thymeleaf.spring4.view.ThymeleafView]: Bean property 'targetBeanName' is not w
ritable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1523) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1231) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.configureBean(AbstractAutowireCapableBeanFactory.java:323) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.thymeleaf.spring4.view.ThymeleafViewResolver.loadView(ThymeleafViewResolver.java:722) ~[thymeleaf-spring4-3.0.2.RELEASE.jar:3.0.2.RELEASE]
        at org.apereo.cas.services.web.RegisteredServiceThemeBasedViewResolver.loadView(RegisteredServiceThemeBasedViewResolver.java:49) ~[cas-server-support-themes-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
        at org.thymeleaf.spring4.view.ThymeleafViewResolver.createView(ThymeleafViewResolver.java:689) ~[thymeleaf-spring4-3.0.2.RELEASE.jar:3.0.2.RELEASE]
        at org.springframework.web.servlet.view.AbstractCachingViewResolver.resolveViewName(AbstractCachingViewResolver.java:146) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.getCandidateViews(ContentNegotiatingViewResolver.java:299) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.view.ContentNegotiatingViewResolver.resolveViewName(ContentNegotiatingViewResolver.java:220) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.resolveViewName(DispatcherServlet.java:1296) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1234) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[catalina.jar:8.5.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[catalina.jar:8.5.8]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.5.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[catalina.jar:8.5.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[catalina.jar:8.5.8]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.6.2.jar:2.6.2]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[catalina.jar:8.5.8]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[catalina.jar:8.5.8]
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.4.2.RELEASE.jar:1.4.2.RELEASE]
...
```

**Comment by mmoayyed** [comment]
Confirmed issue. Thanks!

**Comment by mmoayyed** [comment]
This should be fixed in the latest snapshot versions.
