### ISSUE TITLE
NullPointerException in 5.0.1 with missing dnFormat

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2223]
You get a nullpointerexception if you leave out dnFormat from the LDAP configuration. 

CAS 5.0.1
Tomcat
Steps: Start server with ldap auth, but leave out dnFormat, type AD, login
Stacktrace:
```
2016-12-15 14:53:57,297 WARN [org.apereo.cas.web.flow.resolver.impl.InitialAuthenticationAttemptWebflowEventResolver] -
<null>
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_111]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_111]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_111]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_111]
        at java.util.Formatter.parse(Formatter.java:2547) ~[?:1.8.0_111]
        at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_111]
        at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_111]
        at java.lang.String.format(String.java:2940) ~[?:1.8.0_111]
        at org.ldaptive.auth.FormatDnResolver.resolve(FormatDnResolver.java:148) ~[ldaptive-1.2.0.jar!/:?]
        at org.ldaptive.auth.Authenticator.resolveDn(Authenticator.java:208) ~[ldaptive-1.2.0.jar!/:?]
        at org.ldaptive.auth.Authenticator.authenticate(Authenticator.java:224) ~[ldaptive-1.2.0.jar!/:?]
        at org.apereo.cas.authentication.LdapAuthenticationHandler.authenticateUsernamePasswordInternal(LdapAuthenticationHandler.java:182) ~[cas-server-support-ldap-5.0.1.jar!/:5.0.1]
        at org.apereo.cas.authentication.handler.support.AbstractUsernamePasswordAuthenticationHandler.authenticateUsernamePasswordInternal(AbstractUsernamePasswordAuthenticationHandler.java:82) ~[cas-server-core-authentication-5.0.1.jar!/:
5.0.1]
        at org.apereo.cas.authentication.handler.support.AbstractUsernamePasswordAuthenticationHandler.doAuthentication(AbstractUsernamePasswordAuthenticationHandler.java:64) ~[cas-server-core-authentication-5.0.1.jar!/:5.0.1]
        at org.apereo.cas.authentication.handler.support.AbstractPreAndPostProcessingAuthenticationHandler.authenticate(AbstractPreAndPostProcessingAuthenticationHandler.java:59) ~[cas-server-core-authentication-.0.1.jar!/:5.0.1]
        at org.apereo.cas.authentication.AbstractAuthenticationManager.authenticateAndResolvePrincipal(AbstractAuthenticationManager.java:209) ~[cas-server-core-authentication-5.0.1.jar!/:5.0.1]
        at org.apereo.cas.authentication.PolicyBasedAuthenticationManager.lambda$null$2(PolicyBasedAuthenticationManager
.java:102) ~[cas-server-core-authentication-5.0.1.jar!/:5.0.1]
```

Here is yaml config 
```
cas:
  authn:
    pm: 
      enabled: false
    accept.users: 
    ldap:
      - type: AD
        ldapUrl: ldap://192.168.0.1:389
        useSsl: false
        useStartTls: false
        baseDn: cn=Users,dc=xyz,dc=org
#        dnFormat: '%s@xyz.org'
        userFilter: sAMAccountName={user}
        subtreeSearch: true
        usePasswordPolicy: false
        bindDn: xyz@xyz.org
        bindCredential: P@ssw0rd
        principalAttributeId: sAMAccountName
        principalAttributePassword: unicodePwd
        principalAttributeList: sn, cn, givenName, sAMAccountName 
        allowMultiplePrincipalAttributeValues: true
        additionalAttributes: memberOf
        minPoolSize: 0
        maxPoolSize: 10
        validateOnCheckout: true
        validatePeriodically: true
        validatePeriod: 600
        principalTransformation.caseConversion: LOWERCASE
        failFast: false
```

One other note, some of the documentation refers to ldapUrl that contains multiple servers comma delimited but those don't seem to parse, I could only get a single server to work.

**Comment by mmoayyed** [comment]
https://github.com/apereo/cas/commit/5e5f740141544256c8485026f6e1276ceb5b1ec5

**Comment by mmoayyed** [comment]
I'll review the case with the CSV of Ldap Urls. Thanks very much for the report!

**Comment by mmoayyed** [comment]
On the multiple LDAP url issue, that might be a shortcoming of the docs. Have you tried perhaps separating them by a space character instead of comma?
