### ISSUE TITLE
Upgrading CAS 4.0.1 to 4.2.7 giving 

### ISSUE THREAD

**Issue by binitbhaskar** [apereo/cas#2277]
[ticketRegistry_xml.txt](https://github.com/apereo/cas/files/687717/ticketRegistry_xml.txt)

I am trying to upgrade the CAS server from 4.0.1 to 4.2.7 and done the required changes. When I am trying to start the tomcat, I am getting the following error. I have attached ticketReigisty.xm for the reference.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in ServletContext resource [/WEB-INF/spring-configuration/ticketRegistry.xml]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Use of @OneToMany or @ManyToMany targeting an unmapped class: org.jasig.cas.services.AbstractRegisteredService.properties[org.jasig.cas.services.DefaultRegisteredServiceProperty]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5003)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5517)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1809)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:618)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:301)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:828)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$254(TCPTransport.java:683)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$1/1013669105.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.AnnotationException: Use of @OneToMany or @ManyToMany targeting an unmapped class: org.jasig.cas.services.AbstractRegisteredService.properties[org.jasig.cas.services.DefaultRegisteredServiceProperty]
	at org.hibernate.cfg.annotations.CollectionBinder.bindManyToManySecondPass(CollectionBinder.java:1191)
	at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:794)
	at org.hibernate.cfg.annotations.MapBinder$1.secondPass(MapBinder.java:90)
	at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:54)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1655)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1623)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:278)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:847)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:874)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:340)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:319)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1641)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	... 58 more

Jan 05, 2017 3:32:42 PM org.apache.catalina.core.ApplicationContext log

**Comment by mmoayyed** [comment]
https://apereo.github.io/cas/4.2.x/installation/JPA-Ticket-Registry.html

**Comment by binitbhaskar** [comment]
Hi Misagh,
Thanks for the link. 
I have one query, I am using JPATicketRegistry in 4.0.1. And all the tickets are saved in the database.
I have a table for SERVICETICKET and TICKETGRANTINGTICKET already in our Oracle DB. I am trying to upgrade and got the above issues ? It is to do the Hibernate mapping between AbstractRegisteredService class and DefaultRegisteredServiceProperty.
 @JoinTable(
        name = "RegisteredServiceImpl_Props"
    )
    private Map<String, DefaultRegisteredServiceProperty> properties;

Not sure, if it can solve the issue ?
Is something changed in 4.2.7  wrtt ticket saving ?

**Comment by mmoayyed** [comment]
> Is something changed in 4.2.7 wrtt ticket saving ?

Yes. Schemas are different.

**Comment by binitbhaskar** [comment]
Thanks.

I did the changes but no luck...
Still getting the same error

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in ServletContext resource [/WEB-INF/spring-configuration/ticketRegistry.xml]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Use of @OneToMany or @ManyToMany targeting an unmapped class: org.jasig.cas.services.AbstractRegisteredService.properties[org.jasig.cas.services.DefaultRegisteredServiceProperty]

Any suggestions plz ?  
Do I need to delete any existing tables ? I am wondering if we have any page where  we can see the instructions to upgrade from 4.0.1 to 4.2.0.

**Comment by mmoayyed** [comment]
Start with a clean database.

**Comment by binitbhaskar** [comment]
Hi,

I tried with a fresh local MySQL database. But still getting the same error. I am using maven overley.

###### Log starts ############
2017-01-06 11:18:51,940 WARN [org.springframework.web.context.support.XmlWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in ServletContext resource [/WEB-INF/spring-configuration/ticketRegistry.xml]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: Use of @OneToMany or @ManyToMany targeting an unmapped class: org.jasig.cas.services.AbstractRegisteredService.properties[org.jasig.cas.services.DefaultRegisteredServiceProperty]>
###### Log ends ############

Plz find my cas.properties file.
------------------------------------------------------------------------------------------------------------------
server.name=random.xyz.com

# Services Management URLs.
cas.securityContext.serviceProperties.service=https://random.xyz.com:443/sso/profile/j_acegi_cas_security_check
cas.securityContext.casProcessingFilterEntryPoint.loginUrl=https://random.xyz.com:443/sso/login
cas.securityContext.ticketValidator.casServerUrlPrefix=https://random.xyz.com:443/sso

# Password configuration.
password.defaultSalt=somekey=

ticket.cleaner.database.platform=SQL92

# == Basic database connection pool configuration ==
database.hibernate.dialect=org.hibernate.dialect.MySQLDialect

database.driverClass=com.mysql.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/sso
database.user=root
database.password=

database.pool.minSize=10
database.pool.maxSize=200

# Maximum amount of time to wait in ms for a connection to become
# available when the pool is exhausted
database.pool.maxWait=10000

# Amount of time in seconds after which idle connections
# in excess of minimum size are pruned.
database.pool.maxIdleTime=120

# Number of connections to obtain on pool exhaustion condition.
# The maximum pool size is always respected when acquiring
# new connections.
database.pool.acquireIncrement=5

# == Connection testing settings ==

# Period in s at which a health query will be issued on idle
# connections to determine connection liveliness.
database.pool.idleConnectionTestPeriod=30

# Query executed periodically to test health
database.pool.connectionHealthQuery=SELECT 'x' FROM DUAL

# == Database recovery settings ==

# Number of times to retry acquiring a _new_ connection
# when an error is encountered during acquisition.
database.pool.acquireRetryAttempts=5

# Amount of time in ms to wait between successive aquire retry attempts.
database.pool.acquireRetryDelay=2000

database.hibernate.show.sql=true

staticContentFilter.imgStaticContentUrl=
staticContentFilter.jsStaticContentUrl=

# Messaging properties

#configuration of parameters for accessing the messaging server
protocol=http
mailServerName=
port=18082
messagingPath=
type=POST


# base url of the link sent by email to the user after he attempts to change his email address
changeEmailBaseUrl=${cas.securityContext.casProcessingFilterEntryPoint.loginUrl}

# name of the query string parameter whose value is the code to change the user's email address
changeEmailCodeParameterName=changeEmailCode

# time, in days, until the change email code expiration
changeEmailCodeValidity=2

# time, in days, until the forgotten password code expiration
forgottenPasswordCodeValidity=2

# base url of the link sent by email to the user after a reset password request
forgottenPasswordBaseUrl=${cas.securityContext.casProcessingFilterEntryPoint.loginUrl}

# name of the query string parameter whose value is the code to reset the user's password
forgottenPasswordCodeParameterName=forgottenPasswordCode

# base url of the link sent by email to the user after he registers
emailVerificationBaseUrl=${cas.securityContext.casProcessingFilterEntryPoint.loginUrl}

# name of the query string parameter whose value is the code to verify the user's email address
emailVerificationCodeParameterName=mailVerificationCode


# Settings for the remember me feature


rememberMeMaxAge=
grantingTicketSessionExpirationTimeout=
grantingTicketRememberMeExpirationTimeout=


sso.cookie.domain=.xyz.com

 ticketreg.database.ddl.auto=create-drop
 ticketreg.database.dialect=org.hibernate.dialect.MySQLDialect
 ticketreg.database.batchSize=10
 ticketreg.database.driverClass=com.mysql.jdbc.Driver
 ticketreg.database.url=jdbc:mysql://localhost:3306/sso
 ticketreg.database.user=root
 ticketreg.database.password=root
 ticketreg.database.pool.minSize=10
 ticketreg.database.pool.maxSize=200
 ticketreg.database.pool.maxWait=10000
 ticketreg.database.pool.maxIdleTime=120
 ticketreg.database.pool.acquireIncrement=6
 ticketreg.database.pool.idleConnectionTestPeriod=30
 ticketreg.database.pool.connectionHealthQuery=select 1
 ticketreg.database.pool.acquireRetryAttempts=5
 ticketreg.database.pool.acquireRetryDelay=2000



##
# JPA Service Registry Database Configuration
#
 svcreg.database.ddl.auto=create-drop
# svcreg.database.dialect=org.hibernate.dialect.MySQLInnoDBDialect
 svcreg.database.dialect=org.hibernate.dialect.MySQLDialect
 svcreg.database.hibernate.batchSize=10
 svcreg.database.driverClass=com.mysql.jdbc.Driver
 svcreg.database.url=jdbc:mysql://localhost:3306/sso
 svcreg.database.user=root
 svcreg.database.password=root
 svcreg.database.pool.minSize=6
 svcreg.database.pool.maxSize=18
 svcreg.database.pool.maxWait=10000
 svcreg.database.pool.maxIdleTime=120
 svcreg.database.pool.acquireIncrement=6
 svcreg.database.pool.idleConnectionTestPeriod=30
 svcreg.database.pool.connectionHealthQuery=select 1
 svcreg.database.pool.acquireRetryAttempts=5
 svcreg.database.pool.acquireRetryDelay=2000
-----------------------------------------------------------------------------------------------

Am I missing anything? I think, It is throwing the error when trying to go the Entity class and unable to find entity relationship between AbstractRegisteredService and DefaultRegisteredServiceProperty entity. 

Any help is appreciated. 

Please let me know if you need any logs/configurations.
Thanks.
