### ISSUE TITLE
CAS 5.0.1 NPE with MemcachedTicketRegistryCleaner

### ISSUE THREAD

**Issue by mrcasablr** [apereo/cas#2292]
Hi! 

I'm using CAS 5.0.1 with Oracle JDK 8 with memcached ticket registry - 1.4.15

I consistently see a few of the following in my DEBUG logs - 

2017-01-09 10:37:26,905 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
2017-01-09 10:37:26,914 ERROR [org.springframework.integration.handler.LoggingHandler] - <java.lang.NullPointerException
	at org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner.clean(DefaultTicketRegistryCleaner.java:89)
	at org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner$$FastClassBySpringCGLIB$$29f046b2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.apereo.cas.config.MemcachedTicketRegistryConfiguration$MemcachedTicketRegistryCleaner$$EnhancerBySpringCGLIB$$a7f9a5e5.clean(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

My cas.properties for ticket registry is -

# ticket registry
cas.ticket.registry.memcached.servers=localhost:11211
cas.ticket.registry.memcached.locatorType=ARRAY_MOD
cas.ticket.registry.memcached.failureMode=Redistribute
cas.ticket.registry.memcached.hashAlgorithm=FNV1_64_HASH
cas.ticket.registry.memcached.crypto.signing.key=
cas.ticket.registry.memcached.crypto.signing.keySize=512
cas.ticket.registry.memcached.crypto.encryption.key=
cas.ticket.registry.memcached.crypto.encryption.keySize=16
cas.ticket.registry.memcached.crypto.alg=AES

My cas-gradle-overlay file has -
dependencies {
    compile "org.apereo.cas:cas-server-webapp:${project.'cas.version'}@war"
    compile "org.apereo.cas:cas-server-support-jdbc:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-jdbc-drivers:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-audit-jdbc:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-generic:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-json-service-registry:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-memcached-ticket-registry:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml-core:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml-idp-core:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml-idp:${project.'cas.version'}"
}

Here are a bit more details on the environment -

CAS Version: 5.0.1
Build Date/Time: 2017-01-08T09:25:55Z
System Temp Directory: /tmp
Java Home: /opt/jdk1.8.0_111/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_111
JCE Installed: yes
OS Architecture: amd64
OS Name: Linux
OS Version: 3.10.0-514.2.2.el7.x86_64

Happy to provide more information as needed, Thanks!

**Comment by mmoayyed** [comment]
Thanks. Certainly a bug that needs to be fixed.

**Comment by mmoayyed** [comment]
Is there anything in DEBUG logs before this error? You should always attach full logs so that the error can be traced.

**Comment by mmoayyed** [comment]
Also:

```
cas.ticket.registry.memcached.crypto.signing.key=
cas.ticket.registry.memcached.crypto.signing.keySize=512
cas.ticket.registry.memcached.crypto.encryption.key=
cas.ticket.registry.memcached.crypto.encryption.keySize=16
```

Should be removed. If you have no use for those settings, remove them.

**Comment by mmoayyed** [comment]
See https://apereo.github.io/cas/5.0.x/installation/Configuration-Properties.html#remember

**Comment by mrcasablr** [comment]
Attached are some more logs. I do not see anything else before the exception. This NPE seem to occur frequently at regular intervals - 
[cas.txt](https://github.com/apereo/cas/files/692824/cas.txt)

**Comment by mrcasablr** [comment]
I cleaned up my cas,properties with  keys that were unused.  Here is the log with the first occurrence of the NPE - 

 / / / ___|   / \   / ___| \ \ 
| | | |      / _ \  \___ \  | |
| | | |___  / ___ \  ___) | | |
| |  \____|/_/   \_\|____/  | |
 \_\                       /_/ 

CAS Version: 5.0.1
Build Date/Time: 2017-01-08T09:25:55Z
System Temp Directory: /tmp
Java Home: /opt/jdk1.8.0_111/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_111
JCE Installed: yes
OS Architecture: amd64
OS Name: Linux
OS Version: 3.10.0-514.2.2.el7.x86_64


2017-01-09 12:31:16,866 INFO [org.apereo.cas.web.CasWebApplication] - <The following profiles are active: native>
2017-01-09 12:31:23,607 DEBUG [org.apereo.cas.config.CasEmbeddedContainerConfiguration] - <Creating HTTP configuration for the embedded tomcat container...>
2017-01-09 12:31:23,676 DEBUG [org.apereo.cas.config.CasEmbeddedContainerConfiguration] - <Set HTTP post to 8080>
2017-01-09 12:31:33.873 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=localhost/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2017-01-09 12:31:34,123 INFO [org.apereo.cas.configuration.support.Beans] - <Ticket registry encryption/signing is turned off. This MAY NOT be safe in a clustered production environment. Consider using other choices to handle encryption, signing and verification of ticket registry tickets, and verify the chosen ticket registry does support this behavior.>
2017-01-09 12:31:34,263 INFO [org.apereo.cas.services.AbstractResourceBasedServiceRegistryDao] - <Watching service registry directory at /etc/cas/config>
2017-01-09 12:31:34,270 DEBUG [org.apereo.cas.services.ServiceRegistryConfigWatcher] - <Created service registry watcher for events of type ENTRY_CREATE>
2017-01-09 12:31:34,272 DEBUG [org.apereo.cas.services.AbstractResourceBasedServiceRegistryDao] - <Started service registry watcher thread>
2017-01-09 12:31:34,311 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loading services from JsonServiceRegistryDao>
2017-01-09 12:31:34,529 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:31:34,529 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:31:34,529 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:31:34,529 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 3 services from JsonServiceRegistryDao.>
2017-01-09 12:31:34,624 DEBUG [org.apereo.cas.config.CasPersonDirectoryAttributeRepositoryConfiguration] - <Configured single-row JDBC attribute repository for jdbc:postgresql://localhost:5432/userdb>
2017-01-09 12:31:34,686 DEBUG [org.apereo.cas.config.CasPersonDirectoryAttributeRepositoryConfiguration] - <Configured result attribute mapping for jdbc:postgresql://localhost:5432/userdb to be {uid=email_primary, displayName=first_name, cn=last_name}>
2017-01-09 12:31:34,686 DEBUG [org.apereo.cas.config.CasPersonDirectoryAttributeRepositoryConfiguration] - <No attributes are defined for attribute repositories, or other attribute repository sources are defined>
2017-01-09 12:31:34,695 DEBUG [org.apereo.cas.config.CasPersonDirectoryAttributeRepositoryConfiguration] - <Configured merging strategy for attribute sources is [ADD]>
2017-01-09 12:31:34,755 DEBUG [org.apereo.cas.config.CasPersonDirectoryAttributeRepositoryConfiguration] - <Configured attribute repository sources to merge together: >
2017-01-09 12:31:34,756 DEBUG [org.apereo.cas.config.CasPersonDirectoryAttributeRepositoryConfiguration] - <Configured cache expiration policy for merging attribute sources to be 30 minute(s)>
Hibernate: drop table if exists COM_AUDIT_TRAIL cascade
Hibernate: create table COM_AUDIT_TRAIL (id  bigserial not null, AUD_ACTION varchar(255), APPLIC_CD varchar(255), AUD_CLIENT_IP varchar(255), AUD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null, AUD_RESOURCE varchar(255), AUD_SERVER_IP varchar(255), AUD_USER varchar(255), primary key (id))
2017-01-09 12:31:39,536 DEBUG [org.apereo.cas.config.CasCoreTicketsConfiguration] - <Ticket-granting ticket expiration policy is based on hard/idle timeouts>
2017-01-09 12:31:40,010 INFO [org.apereo.cas.support.saml.OpenSamlConfigBean] - <Initializing OpenSaml configuration...>
2017-01-09 12:31:41,641 DEBUG [org.apereo.cas.support.saml.OpenSamlConfigBean] - <Initialized OpenSaml successfully.>
2017-01-09 12:31:42,131 INFO [org.apereo.cas.support.saml.web.idp.metadata.ShibbolethIdpMetadataAndCertificatesGenerationService] - <Metadata directory location is at [/etc/cas/saml] with entityID [https://cas.example.org/idp]>
2017-01-09 12:31:42,137 DEBUG [org.apereo.cas.support.saml.web.idp.metadata.ShibbolethIdpMetadataAndCertificatesGenerationService] - <Preparing to generate metadata for entityId [https://cas.example.org/idp]>
2017-01-09 12:31:42,137 INFO [org.apereo.cas.support.saml.web.idp.metadata.ShibbolethIdpMetadataAndCertificatesGenerationService] - <Metadata is available at [/etc/cas/saml/idp-metadata.xml]>
2017-01-09 12:31:54,710 DEBUG [org.apereo.cas.configuration.CasConfigurationRebinder] - <Received event org.springframework.cloud.context.environment.EnvironmentChangeEvent[source=[]]>
2017-01-09 12:31:54,710 DEBUG [org.apereo.cas.configuration.CasConfigurationRebinder] - <Reloading CAS configuration via cas-org.apereo.cas.configuration.CasConfigurationProperties>
2017-01-09 12:31:54,908 INFO [org.apereo.cas.configuration.CasConfigurationRebinder] - <Reloaded CAS configuration cas-org.apereo.cas.configuration.CasConfigurationProperties>
2017-01-09 12:31:55,730 DEBUG [org.apereo.cas.util.ResourceUtils] - <No resource defined to prepare. Returning null>
2017-01-09 12:31:55,730 DEBUG [org.apereo.cas.adaptors.generic.ShiroAuthenticationHandler] - <Shiro configuration is not defined>
2017-01-09 12:31:55,746 DEBUG [org.apereo.cas.support.saml.web.view.Saml10SuccessResponseView] - <Using 0 seconds as skew allowance.>
2017-01-09 12:31:55,988 DEBUG [org.apereo.cas.support.saml.web.idp.profile.SSOPostProfileHandlerController] - <Initialized callback service [https://sso.corp.example.com:8443/cas/idp/profile/SAML2/POST/SSO/Callback.+]>
2017-01-09 12:31:56,001 DEBUG [org.apereo.cas.util.RegexUtils] - <Pattern ^(https?|http?)://.* is a valid regex.>
2017-01-09 12:31:56,037 DEBUG [org.apereo.cas.support.saml.web.idp.profile.SLOPostProfileHandlerController] - <Initialized callback service [https://sso.corp.example.com:8443/cas/idp/profile/SAML2/POST/SSO/Callback.+]>
2017-01-09 12:31:56,048 DEBUG [org.apereo.cas.support.saml.web.idp.profile.IdPInitiatedProfileHandlerController] - <Initialized callback service [https://sso.corp.example.com:8443/cas/idp/profile/SAML2/POST/SSO/Callback.+]>
2017-01-09 12:31:56,057 DEBUG [org.apereo.cas.support.saml.web.idp.profile.SSOPostProfileCallbackHandlerController] - <Initialized callback service [https://sso.corp.example.com:8443/cas/idp/profile/SAML2/POST/SSO/Callback.+]>
2017-01-09 12:31:56,412 WARN [org.apereo.cas.util.cipher.WebflowConversationStateCipherExecutor] - <Secret key for signing is not defined. CAS will attempt to auto-generate the signing key>
2017-01-09 12:31:56,434 WARN [org.apereo.cas.util.cipher.WebflowConversationStateCipherExecutor] - <Generated signing key fW0H2RhRCzC2S4toMiT5oOq8BGdW0OCQA0CMyMzGoSPXkTaetcOLKNMs-9LLvGsnYFIVDREYrOinTp_2g4JQ6g of size 512. The generated key MUST be added to CAS settings.>
2017-01-09 12:31:56,435 WARN [org.apereo.cas.util.cipher.WebflowConversationStateCipherExecutor] - <No encryption key is defined. CAS will attempt to auto-generate keys>
2017-01-09 12:31:56,437 WARN [org.apereo.cas.util.cipher.WebflowConversationStateCipherExecutor] - <Generated encryption key fPeBFwQSZhuQOjds of size 16. The generated key MUST be added to CAS settings.>
2017-01-09 12:31:56,596 INFO [org.apereo.cas.config.CasCoreTicketsConfiguration] - <Protocol tickets generated by CAS are not signed/encrypted.>
2017-01-09 12:31:56,842 WARN [org.apereo.cas.util.cipher.TicketGrantingCookieCipherExecutor] - <Secret key for encryption is not defined. CAS will attempt to auto-generate the encryption key>
2017-01-09 12:31:56,843 WARN [org.apereo.cas.util.cipher.TicketGrantingCookieCipherExecutor] - <Generated encryption key xERp3DP34T1h99vOXZe6getn3fAR3Mpux8SaoLPWdNk of size 256. The generated key MUST be added to CAS settings.>
2017-01-09 12:31:56,843 WARN [org.apereo.cas.util.cipher.TicketGrantingCookieCipherExecutor] - <Secret key for signing is not defined. CAS will attempt to auto-generate the signing key>
2017-01-09 12:31:56,843 WARN [org.apereo.cas.util.cipher.TicketGrantingCookieCipherExecutor] - <Generated signing key c-I30wrbG0MPD4NZKQZNUGz_bbklVhBqF1K5lK2WFJe3Mvi4mlqJHTqQhcBDrCXbJFN2qm9mKt4ordsWAzj7zQ of size 512. The generated key MUST be added to CAS settings.>
2017-01-09 12:31:56,849 DEBUG [org.apereo.cas.util.cipher.TicketGrantingCookieCipherExecutor] - <Initialized cipher encryption sequence via [A128CBC-HS256]>
2017-01-09 12:31:56,982 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Initializing CAS webflow configuration...>
2017-01-09 12:31:56,983 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casAuthenticationBlockedView>
2017-01-09 12:31:56,983 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casBadWorkstationView>
2017-01-09 12:31:56,983 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casBadHoursView>
2017-01-09 12:31:56,984 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casAccountLockedView>
2017-01-09 12:31:56,984 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casAccountDisabledView>
2017-01-09 12:31:56,984 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Flow login already contains a definition for state id casAccountDisabledView>
2017-01-09 12:31:56,984 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Created end state state casPasswordUpdateSuccess on flow id login, backed by view factory org.springframework.webflow.mvc.servlet.ServletMvcViewFactory@6fa2ca0>
2017-01-09 12:31:56,984 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casMustChangePassView>
2017-01-09 12:31:56,984 DEBUG [org.apereo.cas.pm.web.flow.PasswordManagementWebflowConfigurer] - <Added view state casExpiredPassView>
2017-01-09 12:31:58,122 INFO [org.apereo.cas.web.CasWebApplication] - <Started CasWebApplication in 45.307 seconds (JVM running for 46.49)>
2017-01-09 12:32:17,615 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loading services from JsonServiceRegistryDao>
2017-01-09 12:32:17,641 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
2017-01-09 12:32:17,647 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:32:17,647 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:32:17,647 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:32:17,647 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 3 services from JsonServiceRegistryDao.>
2017-01-09 12:32:17,662 ERROR [org.springframework.integration.handler.LoggingHandler] - <java.lang.NullPointerException
	at org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner.clean(DefaultTicketRegistryCleaner.java:89)
	at org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner$$FastClassBySpringCGLIB$$29f046b2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.apereo.cas.config.MemcachedTicketRegistryConfiguration$MemcachedTicketRegistryCleaner$$EnhancerBySpringCGLIB$$a7f9a5e5.clean(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
>
2017-01-09 12:33:17,648 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loading services from JsonServiceRegistryDao>
2017-01-09 12:33:17,649 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:33:17,650 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:33:17,650 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-09 12:33:17,650 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 3 services from JsonServiceRegistryDao.>
2017-01-09 12:33:17,663 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
2017-01-09 12:33:17,664 ERROR [org.springframework.integration.handler.LoggingHandler] - <java.lang.NullPointerException
	at org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner.clean(DefaultTicketRegistryCleaner.java:89)
	at org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner$$FastClassBySpringCGLIB$$29f046b2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.apereo.cas.config.MemcachedTicketRegistryConfiguration$MemcachedTicketRegistryCleaner$$EnhancerBySpringCGLIB$$a7f9a5e5.clean(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mmoayyed** [comment]
Very nice. Thanks much! Easy to fix. You able to try 5.0.2-SNAPSHOT when this is fixed?

**Comment by mrcasablr** [comment]
Happy to help. May need some help in getting the SNAPSHOT release going via gradle overlay.

**Comment by mmoayyed** [comment]
Sure thing. You can actually switch right now just to test the basic patch upgrade. Recipe is very simple:

1. Modify your cas.version to point to 5.0.2-SNAPSHOT
2. Follow the command here https://github.com/apereo/cas-gradle-overlay-template#build that deals with SNAPSHOTs.

You also want to make sure this repository is made available to your build:
https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/

I suspect it already is, but please verify. That's all.

When this is fixed, simply re-execute the same command to refresh the snapshot version and have gradle download its latest version. Fix will be auto-applied without any manual work. When 5.0.2 is released, simply switch the version back.

**Comment by mrcasablr** [comment]
I'm on 5.0.2-SNAPSHOT and can see the memcached NPE's. Once the fix is available, I'm all good to test. Thanks for the instructions, they were easy peasey.

**Comment by mrcasablr** [comment]
This bug impacts 5.1.0-RC1 as well.

**Comment by mmoayyed** [comment]
How about 5.1.0-RC2-SNAPSHOT?

**Comment by mmoayyed** [comment]
Please try again with 5.0.2-SNAPSHOT and report back.

**Comment by mrcasablr** [comment]
Fix is working on latest 5.0.2-SNAPSHOT

Here is the log snippet - 
2017-01-10 09:32:39,885 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loading services from JsonServiceRegistryDao>
2017-01-10 09:32:39,886 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
2017-01-10 09:32:39,886 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Finished ticket cleanup.>
2017-01-10 09:32:39,886 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 09:32:39,887 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 09:32:39,887 DEBUG [org.apereo.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 09:32:39,887 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 3 services from JsonServiceRegistryDao.>

Will check on 5.1.0-RC2-SNAPSHOT and report back

**Comment by mrcasablr** [comment]
Tested on latest 5.1.0-RC2-SNAPSHOT 

CAS Version: 5.1.0-RC2-SNAPSHOT
CAS Commit Id: e44590ff094b91f17dab3143668f770f2ff5b67f
CAS Build Date/Time: 2017-01-10T04:36:25Z
Spring Boot Version: 1.4.2.RELEASE
Apache Tomcat Version: Apache Tomcat/8.5.9
---------------------------------------------
System Date/Time: 2017-01-10T10:07:15.296+05:30[Asia/Kolkata]
System Temp Directory: /tmp
---------------------------------------------
Java Home: /opt/jdk1.8.0_111/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_111
JCE Installed: no
---------------------------------------------
OS Architecture: amd64
OS Name: Linux
OS Version: 4.8.15-300.fc25.x86_64

Fix works and no NPE's for memcached.  Snippet of the log -
2017-01-10 10:09:17,268 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Loading services from JsonServiceRegistryDao>
2017-01-10 10:09:17,272 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 10:09:17,272 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 10:09:17,272 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https|imaps)://.*>
2017-01-10 10:09:17,273 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^https://www.apereo.org>
2017-01-10 10:09:17,273 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 10:09:17,273 INFO [org.apereo.cas.services.DefaultServicesManager] - <Loaded 5 services from JsonServiceRegistryDao.>
2017-01-10 10:09:17,276 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
2017-01-10 10:09:17,277 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Finished ticket cleanup.>
2017-01-10 10:10:17,273 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Loading services from JsonServiceRegistryDao>
2017-01-10 10:10:17,277 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 10:10:17,277 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 10:10:17,277 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https|imaps)://.*>
2017-01-10 10:10:17,277 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^https://www.apereo.org>
2017-01-10 10:10:17,277 DEBUG [org.apereo.cas.services.DefaultServicesManager] - <Adding registered service ^(https?|http?)://.*>
2017-01-10 10:10:17,277 INFO [org.apereo.cas.services.DefaultServicesManager] - <Loaded 5 services from JsonServiceRegistryDao.>
2017-01-10 10:10:17,277 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Releasing ticket cleanup lock.>
2017-01-10 10:10:17,278 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Finished ticket cleanup.>

**Comment by mmoayyed** [comment]
Thanks for confirming.
