### ISSUE TITLE
5.1.0-RC2-SNAPSHOT: GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 2.4.7 and you are trying to load version 2.4.8

### ISSUE THREAD

**Issue by mrcasablr** [apereo/cas#2384]
Hello! 
Here is my build environment -
```
OS: CentOS Linux 7 x86-64 
JDK: Oracle JDK 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
I see the following error in cas logs when compiling 5.1.0-RC2-SNAPSHOT with some cas modules.

```
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 2.4.7 and you are trying to load version 2.4.8
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:512) ~[groovy-2.4.7.jar!/:2.4.7]
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:80) ~[groovy-2.4.7.jar!/:2.4.7]
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:74) ~[groovy-2.4.7.jar!/:2.4.7]
	at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:56) ~[groovy-2.4.7.jar!/:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:113) ~[groovy-2.4.7.jar!/:2.4.7]
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:74) ~[groovy-2.4.7.jar!/:2.4.7]
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36) ~[groovy-2.4.7.jar!/:2.4.7]
	... 27 more
2017-02-12 10:36:16,017 WARN [org.springframework.boot.SpringApplication] - <Error handling failed (no error message)>
2017-02-12 10:36:16,017 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
```

In an email thread, it was suggested the `cas/build.gradle` has proper gradle cas imports. These were untouched and are at the following defaults -
```
apply from: 'http://dl.bintray.com/scalding/generic/waroverlay.gradle'
apply from: 'https://raw.githubusercontent.com/apereo/cas/5.0.x/gradle/overrides.gradle'
```

Here are the steps to reproduce this issue, first when everything is working and on adding cas modules cas breaks -

```
$ https://github.com/apereo/cas-gradle-overlay-template.git
$ cd cas-gradle-overlay-template/
```

* Edit gradle.properties
```
cas.version=5.0.2
to
cas.version=5.1.0-RC2-SNAPSHOT
```
```
# rm -rf /root/.gradle
# ./gradlew clean build --parallel --refresh-dependencies
```
* On successful build, execute 
```
# java -jar cas/build/libs/cas.war
```

* Login to `http://localhost:8080/cas/login` works with default `casuser/Mellon`

Everything works as expected. Now to adding modules -

* Add the following cas modules to cas/build.gradle
```
    compile "org.apereo.cas:cas-server-webapp:${project.'cas.version'}@war"
    compile "org.apereo.cas:cas-server-support-jdbc:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-jdbc-drivers:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-audit-jdbc:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-generic:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-json-service-registry:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml-core:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml-idp-core:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-saml-idp:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-redis-ticket-registry:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-oauth:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-oauth-core:${project.'cas.version'}"
    compile "org.apereo.cas:cas-server-support-oauth-webflow:${project.'cas.version'}"
```

* Remove gradle cache and compile as before and start cas
```
# rm -rf /root/.gradle
# ./gradlew clean build --parallel --refresh-dependencies
# java -jar cas/build/libs/cas.war
```
CAS fails to start with groovy error

/etc/cas was untouched and were all defaults.

Attached is the cas.log
[cas.txt](https://github.com/apereo/cas/files/769088/cas.txt)

**Comment by mmoayyed** [comment]
As you noted, this is the problem:

> In an email thread, it was suggested the cas/build.gradle has proper gradle cas imports. These were untouched and are at the following defaults -

```
apply from: 'http://dl.bintray.com/scalding/generic/waroverlay.gradle'
apply from: 'https://raw.githubusercontent.com/apereo/cas/5.0.x/gradle/overrides.gradle'
```

**Comment by rdev5** [comment]
I'm now getting the same error rebuilding my CAS-5.1.1-SNAPSHOT:
````
groovy-jsr223 is loaded in version 2.4.11 and you are trying to load version 2.4.10
````

However, we're using the following line in `build.gradle`:
````
apply from: 'https://raw.githubusercontent.com/apereo/cas/5.1.x/gradle/overrides.gradle'
````

Change appears to have been since https://github.com/apereo/cas/commit/06c845b95f934aa64d5bb3caf223bb6d30eb7dbe#diff-9b48f335454c4706fd0d70a5b0cdf7e2

**Comment by rdev5** [comment]
FYI, I had to back down this line to the previous commit to get it working again:

````
apply from: 'https://raw.githubusercontent.com/apereo/cas/4ead6e9d77bf53d186149fdc09ee0121980576e8/gradle/overrides.gradle'
````

Will have to do more testing, but the application is at least functional again at CAS-5.1.1-SNAPSHOT.
