### ISSUE TITLE
Deploy of CAS 5.0.4 in JBoss Wildfly 10.1.0 succeeds, but requests fail

### ISSUE THREAD

**Issue by mmxkcd** [apereo/cas#2511]
Deploying CAS 5.0.4 in JBoss Wildfly 10.1.0 succeeds, but no successful http requests are possible.

The following stacktrace occurs when trying to access the deployment:

```
[org.springframework.boot.web.support.ErrorPageFilter] (default task-10) Forwarding to error page from request [/] due to exception [value is null]: java.lang.NullPointerException: value is null
	at org.jboss.logmanager.MDC.putObject(MDC.java:78)
	at org.jboss.logmanager.MDC.put(MDC.java:62)
	at org.slf4j.impl.Slf4jMDCAdapter.put(Slf4jMDCAdapter.java:32)
	at org.slf4j.MDC.put(MDC.java:116)
	at org.apereo.cas.logging.web.ThreadContextMDCServletFilter.doFilter(ThreadContextMDCServletFilter.java:55)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
```

It seems to me, that the Wildfly MDC implementation does not allow null values.

**Comment by mmoayyed** [comment]
Yes I think some of the request properties are null; In your case I am guessing it's `request.getRemoteUser()`. You could add null-checks into `ThreadContextMDCServletFilter` and shoot over the changes. That should take care of this.

**Comment by trampi** [comment]
fixed by https://github.com/apereo/cas/commit/ceee39d78215c9aca11c4d83b0a255a6fa57c04f

**Comment by mmoayyed** [comment]
No, that's incorrect. That only fixes master. Not 5.0.4.
