### ISSUE TITLE
Service provider integration issue

### ISSUE THREAD

**Issue by nareshkankti** [apereo/cas#2535]
[Service provider integration issue.txt](https://github.com/apereo/cas/files/930111/Service.provider.integration.issue.txt)

**Comment by mmoayyed** [comment]
Please describe the issue in markdown using the github template. Not as a text file.

**Comment by mmoayyed** [comment]
Also please rename the issue to be exact and explicit.

**Comment by mmoayyed** [comment]
Closing due to inactivity. Feel free to resume and act on the above changes, and we'd be happy to review and make suggestions.

**Comment by nareshkankti** [comment]
# Issue with Tableau integration using SAML IDP 
# CAS generating invalid json hence SAML service registration is failing 
## CAS server version: 5.1.0-RC2
## Container/environment type/version: Tomcat 8 on Windows
##  SAML jars added to pom.xml
	1. cas-server-support-saml
	2. cas-server-support-saml-core
	3. cas-server-support-saml-idp
	4. cas-server-support-saml-idp-core
	5. cas-server-support-saml-sp-integrations
## Properties set are:
	1. cas.samlSP.tableau.metadata=/etc/cas/idp/metadata/Tablea_xml.xml
	2. cas.samlSP.tableau.name=Tableau
	3. cas.samlSP.tableau.description=Tableau Integration
	4. cas.samlSP.tableau.attributes=username
## Issue Description:
	1. I am trying to establish SSO for Tableau application using SAML IDP. As part of it,included required
	SAML jars in CAS application pom.xml.
	2. After deploying CAS on Tomcat 8, CAS loaded SamlRegisteredService and immediately started throwing below exception
		Adding registered service [^https://www.apereo.org]
		Adding registered service [^(https|imaps|http)://.*]
		Adding registered service [https://tst-reports.example.com]
		Loaded [3] service(s) from [JsonServiceRegistryDao].
		INFO [org.apereo.cas.services.DefaultServicesManager] - <Loaded [3] service(s) from [JsonServiceRegistryDao].>
		Exception in thread "org.apereo.cas.services.JsonServiceRegistryDao" 2017-04-18 04:51:20,802 WARN [org.apereo.cas.services.ServiceRegistryConfigWatcher] - <Directory key is no longer valid. Quitting watcher service>
		java.nio.file.ClosedWatchServiceException
		at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80)
		at sun.nio.fs.AbstractWatchService.checkKey(AbstractWatchService.java:92)
		at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:119)
		at org.apereo.cas.services.ServiceRegistryConfigWatcher.run(ServiceRegistryConfigWatcher.java:72)
		at java.lang.Thread.run(Thread.java:745)
	3. After throwing above exception, CAS server application rebootes and this continues.
	4. After analysis found that *cas-server-support-saml-sp-integrations*, generating Tableau-(random number).json which is in invalid JSON 
	   format and causing service registration issue.
	5. Below are the sevice registrations, using in my application
		{
			"@class" : "org.apereo.cas.services.RegexRegisteredService",
			"serviceId" : "^(https|imaps|http)://.*",
			"name" : "HTTPS and IMAPS",
			"id" : 10000001,
			"description" : "This service definition authorizes all application urls that support HTTPS and IMAPS protocols.",
			"evaluationOrder" : 10000,
			"attributeReleasePolicy" : {
			"@class" : "org.apereo.cas.services.ReturnAllAttributeReleasePolicy",
			"principalAttributesRepository" : {
			"@class" : "org.apereo.cas.authentication.principal.cache.CachingPrincipalAttributesRepository",
			"duration" : {
			"@class" : "javax.cache.expiry.Duration",
			"timeUnit" : [ "java.util.concurrent.TimeUnit", "HOURS" ],
			"expiration" : 2,
			"mergingStrategy" : "MULTIVALUED"
			},
			"mergingStrategy" : "MULTIVALUED"
			}
			}
		}
	6. SamlRegisteredService generated by CAS 5.1.0-RC2 for Tableau service which I observed as invalid JSON format
		{
			@class: org.apereo.cas.support.saml.services.SamlRegisteredService
			serviceId: https://tst-reports.example.com
			name: Tableau
			id: 10000003
			description: Tableau Integration
			proxyPolicy:
			{
			@class: org.apereo.cas.services.RefuseRegisteredServiceProxyPolicy
			}
			evaluationOrder: 10000002
			usernameAttributeProvider:
			{
			@class: org.apereo.cas.services.DefaultRegisteredServiceUsernameProvider
			}
			attributeReleasePolicy:
			{
			@class: org.apereo.cas.services.ReturnAllowedAttributeReleasePolicy
			principalAttributesRepository:
			{
			@class: org.apereo.cas.authentication.principal.DefaultPrincipalAttributesRepository
			expiration: 2
			timeUnit: HOURS
			}
			authorizedToReleaseCredentialPassword: false
			authorizedToReleaseProxyGrantingTicket: false
			excludeDefaultAttributes: false
			allowedAttributes:
			[
			java.util.ArrayList
			[
			username
			]
			]
			}
			multifactorPolicy:
			{
			@class: org.apereo.cas.services.DefaultRegisteredServiceMultifactorPolicy
			failureMode: CLOSED
			bypassEnabled: false
			}
			accessStrategy:
			{
			@class: org.apereo.cas.services.DefaultRegisteredServiceAccessStrategy
			enabled: true
			ssoEnabled: true
			requireAllAttributes: true
			caseInsensitive: false
			}
			metadataLocation: /etc/cas/idp/metadata/Tablea_xml.xml
			metadataMaxValidity: 0
			metadataCriteriaDirection: INCLUDE
			metadataCriteriaPattern: https://tst-reports.example.com
			signAssertions: false
			signResponses: true
			encryptAssertions: false
			metadataCriteriaRoles: SPSSODescriptor
			metadataCriteriaRemoveEmptyEntitiesDescriptors: true
			metadataCriteriaRemoveRolelessEntityDescriptors: true
		}

**Comment by mmoayyed** [comment]
What is invalid about the JSON format?

**Comment by mmoayyed** [comment]
I dont see it. It just says "SamlRegisteredService generated by CAS 5.1.0-RC2 for Tableau service which I observed as invalid JSON format". What is invalid about it?

**Comment by nareshkankti** [comment]
I may be wrong but it is not like json mentioned in point# 5. key value pair in double codes.

**Comment by mmoayyed** [comment]
This is all good. Study https://hjson.org/

**Comment by nareshkankti** [comment]
I have validated Point#6 json with https://jsonformatter.curiousconcept.com/. which says invalid

**Comment by nareshkankti** [comment]
On every deployment of CAS application, it generates tableau json again with different random number appended and json registration service increases the number of services by one.
Example: when I deploy first time on the server after cleaning server deployment directory, service says registered 3 services
Adding registered service [^https://www.apereo.org]
Adding registered service [^(https|imaps|http)://.*]
Adding registered service [https://tst-reports.example.com]
Loaded [3] service(s) from [JsonServiceRegistryDao].
##Next stop the server and run server again, CAS registers Tableau service multiple times.
Adding registered service [^https://www.apereo.org]
Adding registered service [^(https|imaps|http)://.*]
Adding registered service [https://tst-reports.example.com]
Adding registered service [https://tst-reports.example.com]
Loaded [4] service(s) from [JsonServiceRegistryDao].
Same service is registered multiple times

**Comment by yinzhi7** [comment]
Did you figure out how to integrate tableau with cas?..
