### ISSUE TITLE
unable to start CAS with OIDC in version 5.1.0-RC3 (getting missing bean error)

### ISSUE THREAD

**Issue by leeyc0** [apereo/cas#2538]
- CAS server version: 5.1.0-RC3
- Container/environment type/version: Tomcat

I got bean error in starting CAS (see below). Seems that AuthenticationServiceSelectionStrategy is missing required bean annotation?

```
2017-04-21 11:10:50,219 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'oidcConfiguration': Unsatisfied dependency expressed through field 'oauth20AuthenticationServiceSelectionStrategy'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.authentication.AuthenticationServiceSelectionStrategy' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=oauth20AuthenticationServiceSelectionStrategy)}>
2017-04-21 11:10:50,230 WARN [org.apereo.cas.services.ServiceRegistryConfigWatcher] - <Directory key is no longer valid. Quitting watcher service>
Exception in thread "org.apereo.cas.services.JsonServiceRegistryDao" java.nio.file.ClosedWatchServiceException
        at sun.nio.fs.AbstractWatchService.checkOpen(AbstractWatchService.java:80)
        at sun.nio.fs.AbstractWatchService.checkKey(AbstractWatchService.java:92)
        at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:119)
        at org.apereo.cas.services.ServiceRegistryConfigWatcher.run(ServiceRegistryConfigWatcher.java:72)
        at java.lang.Thread.run(Thread.java:745)
2017-04-21 11:10:50,461 ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] - <

***************************
APPLICATION FAILED TO START
***************************

Description:

Field oauth20AuthenticationServiceSelectionStrategy in org.apereo.cas.oidc.config.OidcConfiguration required a bean of type 'org.apereo.cas.authentication.AuthenticationServiceSelectionStrategy' that could not be found.


Action:

Consider defining a bean of type 'org.apereo.cas.authentication.AuthenticationServiceSelectionStrategy' in your configuration.
```

**Comment by leeyc0** [comment]
ref:
https://github.com/apereo/cas/blob/v5.1.0-RC3/support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java#L150

https://github.com/apereo/cas/blob/a8458ce73a7149ab5a0cc93b8d0a31b8cc3f5f12/support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthAuthenticationServiceSelectionStrategyConfiguration.java#L44

It looks like the qualifier at OidcConfiguration.java#L150 should be oauth20AuthenticationRequestServiceSelectionStrategy? Maybe I have to edit the source code to check...

**Comment by leeyc0** [comment]
After applying this one-line fix, the CAS server appears to be running, but I need time to test OIDC functionalities if this fix is correct

```
--- a/support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
+++ b/support/cas-server-support-oidc/src/main/java/org/apereo/cas/oidc/config/OidcConfiguration.java
@@ -147,7 +147,7 @@ public class OidcConfiguration extends WebMvcConfigurerAdapter {
     private AuthenticationSystemSupport authenticationSystemSupport;
 
     @Autowired
-    @Qualifier("oauth20AuthenticationServiceSelectionStrategy")
+    @Qualifier("oauth20AuthenticationRequestServiceSelectionStrategy")
     private AuthenticationServiceSelectionStrategy oauth20AuthenticationServiceSelectionStrategy;
 
     @Autowired
```

**Comment by leeyc0** [comment]
After I patched OidcConfiguration.java, now I got JSON deserialization error as shown below, have another hard time to find the cause...

```
2017-04-21 19:44:29,694 ERROR [org.apereo.cas.util.serialization.AbstractJacksonBackedStringSerializer] - <Cannot read/parse JSON [{"@class":"org.apereo.cas.ticket.code.OAuthCodeImpl","@id":1,"expirationPolicy":{"@class":"org.ap...] to deserialize into type [interface org.apereo.cas.ticket.ServiceTicket]. This may be caused in the absence of a configuration/support module that knows how to interpret the JSON fragment, specially if the fragment describes a CAS registered service definition. Internal parsing error is [Can not construct instance of org.apereo.cas.ticket.code.OAuthCodeExpirationPolicy: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"@class":"org.apereo.cas.ticket.code.OAuthCodeImpl","@id":1,"expirationPolicy":{"@class":"org.apereo.cas.ticket.code.OAuthCodeExpirationPolicy","timeToKillInSeconds":30,"numberOfUses":1,"timeToLive":30},"id":"OC-4-tf0PYydkl3cOtEcbjlNNQuFEkevHZN1MxMp","lastTimeUsed":1492775069.645,"creationTime":1492775069.645,"countOfUses":0,"service":{"@class":"org.apereo.cas.authentication.principal.SimpleWebApplicationServiceImpl","id":"http://soekris:5000/oidc_callback","originalUrl":"http://soekris:5000/oidc_callback","loggedOutAlready":false},"authentication":{"@class":"org.apereo.cas.authentication.DefaultAuthentication","authenticationDate":1492775069.644,"credentials":["java.util.ArrayList",[{"@class":"org.apereo.cas.authentication.BasicCredentialMetaData","id":"yclee","credentialClass":"org.apereo.cas.authentication.BasicIdentifiableCredential"}]],"principal":{"@class":"org.apereo.cas.authentication.principal.SimplePrincipal","id":"yclee"},"attributes":{"@class":"java.util.HashMap","isFromNewLogin":"true","bypassMultifactorAuthentication":"false","authenticationDate":"2017-04-21T11:38:14.841Z[UTC]","authnContextClass":"mfa-gauth","roles":["java.util.Collections$UnmodifiableSet",[]],"successfulAuthenticationHandlers":["java.util.LinkedList",["clustertech","GoogleAuthenticatorAuthenticationHandler"]],"nonce":"","samlAuthenticationStatementAuthMethod":"urn:oasis:names:tc:SAML:1.0:am:password","authenticationMethod":["java.util.LinkedList",["clustertech","GoogleAuthenticatorAuthenticationHandler"]],"permissions":["java.util.Collections$UnmodifiableSet",[]],"longTermAuthenticationRequestTokenUsed":"false","state":"{\"csrf_token\": \"3nnXVsp6gA3QZzrLSqwi/iYwXQkJWh2g\", \"destination\": \"eyJhbGciOiJIUzI1NiJ9.Imh0dHA6Ly9zb2VrcmlzOjUwMDAvbG9naW4i.lTMFvmnw0-1tc9oRYzhYlc4OGAM1rT-PnDdff3GDK6c\"}"},"successes":{"@class":"java.util.HashMap","org.pac4j.cas.profile.CasProfile":{"@class":"org.apereo.cas.authentication.DefaultHandlerResult","handlerName":"org.pac4j.cas.profile.CasProfile","credentialMetaData":{"@class":"org.apereo.cas.authentication.BasicCredentialMetaData","id":"yclee","credentialClass":"org.apereo.cas.authentication.BasicIdentifiableCredential"},"principal":{"@class":"org.apereo.cas.authentication.principal.SimplePrincipal","id":"yclee"}}}},"prefix":"OC","fromNewLogin":true,"expired":false,"expiredInternal":false}; line: 1, column: 146] (through reference chain: org.apereo.cas.ticket.code.OAuthCodeImpl["expirationPolicy"])]>
2017-04-21 19:44:29,695 ERROR [org.apereo.cas.ticket.registry.MongoDbTicketRegistry] - <Failed fetching [OC-4-tf0PYydkl3cOtEcbjlNNQuFEkevHZN1MxMp]: [INVALID_TICKET]>
2017-04-21 19:44:29,695 ERROR [org.apereo.cas.support.oauth.web.response.accesstoken.ext.AccessTokenAuthorizationCodeGrantRequestExtractor] - <Code or refresh token expired: [null]>
2017-04-21 19:44:29,695 ERROR [org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController] - <Access token request verification fails>
org.apereo.cas.ticket.InvalidTicketException: OC-4-tf0PYydkl3cOtEcbjlNNQuFEkevHZN1MxMp
        at org.apereo.cas.support.oauth.web.response.accesstoken.ext.AccessTokenAuthorizationCodeGrantRequestExtractor.extract(AccessTokenAuthorizationCodeGrantRequestExtractor.java:52) ~[cas-server-support-oauth-5.1.0-RC3.jar:5.1.0-RC3]
        at org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController.examineAndExtractAccessTokenGrantRequest(OAuth20AccessTokenEndpointController.java:187) ~[cas-server-support-oauth-5.1.0-RC3.jar:5.1.0-RC3]
        at org.apereo.cas.support.oauth.web.endpoints.OAuth20AccessTokenEndpointController.handleRequest(OAuth20AccessTokenEndpointController.java:109) ~[cas-server-support-oauth-5.1.0-RC3.jar:5.1.0-RC3]
        at org.apereo.cas.oidc.web.controllers.OidcAccessTokenEndpointController.handleRequest(OidcAccessTokenEndpointController.java:53) ~[cas-server-support-oidc-5.1.0-RC3.jar:5.1.0-RC3]
        at org.apereo.cas.oidc.web.controllers.OidcAccessTokenEndpointController$$FastClassBySpringCGLIB$$60cb7b7e.invoke(<generated>) ~[cas-server-support-oidc-5.1.0-RC3.jar:5.1.0-RC3]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656) ~[spring-aop-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apereo.cas.oidc.web.controllers.OidcAccessTokenEndpointController$$EnhancerBySpringCGLIB$$91b6ef8a.handleRequest(<generated>) ~[cas-server-support-oidc-5.1.0-RC3.jar:5.1.0-RC3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) ~[servlet-api.jar:?]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[servlet-api.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-websocket.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apereo.cas.web.support.AuthenticationCredentialsLocalBinderClearingFilter.doFilter(AuthenticationCredentialsLocalBinderClearingFilter.java:28) ~[cas-server-core-web-5.1.0-RC3.jar:5.1.0-RC3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apereo.cas.security.RequestParameterPolicyEnforcementFilter.doFilter(RequestParameterPolicyEnforcementFilter.java:261) ~[cas-server-security-filter-2.0.6.jar:2.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apereo.cas.security.ResponseHeadersEnforcementFilter.doFilter(ResponseHeadersEnforcementFilter.java:238) ~[cas-server-security-filter-2.0.6.jar:2.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apereo.inspektr.common.web.ClientInfoThreadLocalFilter.doFilter(ClientInfoThreadLocalFilter.java:64) ~[inspektr-common-1.7.GA.jar:1.7.GA]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:108) ~[spring-boot-actuator-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apereo.cas.logging.web.ThreadContextMDCServletFilter.doFilter(ThreadContextMDCServletFilter.java:90) ~[cas-server-core-logging-5.1.0-RC3.jar:5.1.0-RC3]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) ~[spring-boot-actuator-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.8.1.jar:2.8.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94) ~[catalina.jar:8.0.41]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) ~[catalina.jar:8.0.41]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) ~[catalina.jar:8.0.41]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) ~[catalina.jar:8.0.41]
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676) ~[catalina.jar:8.0.41]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) ~[catalina.jar:8.0.41]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509) ~[catalina.jar:8.0.41]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104) ~[tomcat-coyote.jar:8.0.41]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) ~[tomcat-coyote.jar:8.0.41]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1524) ~[tomcat-coyote.jar:8.0.41]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480) ~[tomcat-coyote.jar:8.0.41]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.0.41]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by mmoayyed** [comment]
Please turn the change into a pull request and then submit. Thanks for the diagnosis.

**Comment by leeyc0** [comment]
Sure I will change it to PR but I still need further debugging first. The code is still not running at the moment, however I am already getting progress. The problem is now in JSON serialization after the bean bug is fixed.

**Comment by mmoayyed** [comment]
Excellent. Thanks!

What does your JSON look like?

**Comment by mmoayyed** [comment]
Also please switch to RC4-SNAPSHOT, if you're running the overlay.

**Comment by leeyc0** [comment]
There are several issues:

1. In OAuth20CasAuthenticationBuilder.java, the attributes "permissions" and "roles" are serialized into java.util.Collections$UnmodifiableSet (which profile.getPermissions() and profile.getRoles() returns), but it cannot be deserialized. The fix of this problem is simply wrap getPermissions and getRoles with new HashSet().

2. I believe OAuthCodeExpirationPolicy.java and MultiTimeUseOrTimeoutExpirationPolicy.java, the property timeToKillInSeconds should be renamed timeToLive, other I would get a JSON mixed with timeToLive and timeToKillInSeconds which cannot be deserialized.

[bugjson.txt](https://github.com/apereo/cas/files/947385/bugjson.txt)

**Comment by mmoayyed** [comment]
Thanks. Who is generating the CAS JSON service defn?

**Comment by mmoayyed** [comment]
Or perhaps, the better question, is how?

**Comment by leeyc0** [comment]
Just create a PR, which should be a fix.

BTW I am still getting null TGT error, which I believe to be unrelated anyway. Do you have any clue?

```
2017-04-21 23:38:41,872 ERROR [org.apereo.cas.support.oauth.web.endpoints.OAuth20UserProfileControllerController] - <Ticket granting ticket [null] parenting access token [AT-7-Jm3HYWdzOjXdIWKiDpPCh0OggogveREOBQn] has expired>
2017-04-21 23:38:41,957 ERROR [org.apereo.cas.support.oauth.web.endpoints.OAuth20UserProfileControllerController] - <Ticket granting ticket [null] parenting access token [AT-8-AHsQSpjTdYkAUFp1DENL6T2Keb2j6QQDaNS] has expired>
2017-04-21 23:38:42,042 ERROR [org.apereo.cas.support.oauth.web.endpoints.OAuth20UserProfileControllerController] - <Ticket granting ticket [null] parenting access token [AT-9-SXHne4MdXIFdElVmTV6DcKD9iJPipATewQk] has expired>
```

**Comment by mmoayyed** [comment]
Is this with RC4 SNAPSHOT?

**Comment by leeyc0** [comment]
Oh yes you reminded me. I forgot to rebuild the war in master
(The PR itself is referenced to master, don't worry)

**Comment by mmoayyed** [comment]
Very good. Post back if you see the same issue there, and thanks for the PR! I'll let the CI build the PR and then will merge. very good work!

**Comment by leeyc0** [comment]
After hard debugging time, the issue turns out to be another JSON serialization issue: missing yet another JsonProperty annotation...
