### ISSUE TITLE
"authenticationFailure.PrincipalException" missing in messages.properties. Use "screen.service.error.message"

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2592]
I updated to the latest 5.1.0-SNAPSHOT and got the following error message during login:

`authenticationFailure.PrincipalException`

With the following stack trace in the log:
```
ERROR [org.apereo.cas.web.flow.resolver.impl.AbstractCasWebflowEventResolver] - <screen.service.error.message>
org.apereo.cas.authentication.PrincipalException: screen.service.error.message
	at org.apereo.cas.services.RegisteredServiceAccessStrategyUtils.ensurePrincipalAccessIsAllowedForService(RegisteredServiceAccessStrategyUtils.java:94) ~[cas-server-core-services-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
	at org.apereo.cas.DefaultCentralAuthenticationService.createTicketGrantingTicket(DefaultCentralAuthenticationService.java:362) ~[cas-server-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
	at org.apereo.cas.DefaultCentralAuthenticationService$$FastClassBySpringCGLIB$$b02e48f2.invoke(<generated>) ~[cas-server-core-5.1.0-SNAPSHOT.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85) ~[spring-aop-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.apereo.inspektr.audit.AuditTrailManagementAspect.handleAuditTrail(AuditTrailManagementAspect.java:134) ~[inspektr-audit-1.7.GA.jar:1.7.GA]
	...
```

This was caused by a change in default Attribute Release policy (iirc the default was Return All, but now it is Return Allowed, with no attributes selected). The absence of released attributes caused the Required Attribute access strategy to fail.

I fixed the Attribute Release policy in the service registry and everything is working again.

Now only the error message itself needs fixing:
It should have displayed the error message for "screen.service.error.message" instead of "authenticationFailure.PrincipalException" (which has no associated text in messages.properties).

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new 5.1 SNAPSHOT.

**Comment by Condor70** [comment]
Not completely fixed yet.

I'm still getting the same error when using mfa-gauth.
