### ISSUE TITLE
JPA service management web app fails to init underlying DB (Oracle)

### ISSUE THREAD

**Issue by jhitt25** [apereo/cas#2707]
CAS: 5.1.0
DB: Oracle 12c (12.1.0.1.0) - though this would affect all versions of Oracle below 12.1 as well

Plain cas-management application, with the following serviceRegistry settings:

```
cas.serviceRegistry.jpa.url=jdbc:oracle:thin:@myserver.example.com:1521:mydatabase
cas.serviceRegistry.jpa.dialect=org.hibernate.dialect.Oracle12cDialect
cas.serviceRegistry.jpa.defaultSchema=cas5_server
cas.serviceRegistry.jpa.user=cas5_server
cas.serviceRegistry.jpa.password=cas5_server
cas.serviceRegistry.jpa.healthQuery=SELECT 1 FROM DUAL
cas.serviceRegistry.jpa.ddlAuto=update
cas.serviceRegistry.jpa.driverClass=oracle.jdbc.OracleDriver
cas.serviceRegistry.jpa.pool.minSize=3
cas.serviceRegistry.jpa.pool.maxSize=10
cas.serviceRegistry.initFromJson=true
```

When running, the relevant portion of the log is:

```
Jun 22 17:53:23 web3-test java: Hibernate: create table cas5_server.RegexRegisteredService (expression_type VARCHAR(15) DEFAULT 'ant' not null, id number(19,0) not null, access_strategy blob, attribute_release blob, description varchar2(255 char), evaluation_order number(10,0) not null, informationUrl varchar2(255 char), logo varchar2(255 char), logout_type number(10,0), logout_url varchar2(255 char), mfa_policy blob, name varchar2(255 char) not null, privacyUrl varchar2(255 char), proxy_policy blob, public_key blob, required_handlers blob, serviceId varchar2(255 char) not null, theme varchar2(255 char), username_attr blob, bypassApprovalPrompt number(1,0), clientId varchar2(255 char), clientSecret varchar2(255 char), generateRefreshToken number(1,0), jsonFormat number(1,0), supported_grants blob, supported_responses blob, DYNAMIC_REG_TIME timestamp, dynamicallyRegistered number(1,0), encryptIdToken number(1,0), idTokenEncryptionAlg varchar2(255 char), idTokenEncryptionEncoding varchar2(255 char), implicit number(1,0), jwks varchar2(255 char), scopes blob, signIdToken number(1,0), encryptAssertions number(1,0), metadataCriteriaDirection varchar2(255 char), metadataCriteriaPattern varchar2(255 char), metadataCriteriaRemoveEmptyEntitiesDescriptors number(1,0), metadataCriteriaRemoveRolelessEntityDescriptors number(1,0), metadataCriteriaRoles varchar2(255 char), metadataLocation varchar2(255 char), metadataMaxValidity number(19,0), metadataSignatureLocation varchar2(255 char), nameIdQualifier varchar2(255 char), requiredAuthenticationContextClass varchar2(255 char), requiredNameIdFormat varchar2(255 char), serviceProviderNameIdQualifier varchar2(255 char), signAssertions number(1,0), signResponses number(1,0), primary key (id))
Jun 22 17:53:23 web3-test java: 2017-06-22 17:53:23,961 WARN [org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl] - <GenerationTarget encountered exception accepting command : Error executing DDL via JDBC Statement>
Jun 22 17:53:23 web3-test java: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement
Jun 22 17:53:23 web3-test java: at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.2.10.Final.jar!/:5.2.10.Final]
.
.
.
Jun 22 17:53:24 web3-test java: Caused by: java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long
Jun 22 17:53:24 web3-test java: at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) ~[ojdbc7-1.7.jar!/:12.1.0.2.0]
```

The specific identifiers in the generated statement that are too long are: metadataCriteriaRemoveEmptyEntitiesDescriptors, metadataCriteriaRemoveRolelessEntityDescriptors, serviceProviderNameIdQualifier, and requiredAuthenticationContextClass.
Oracle prior to 12.2 does not support identifiers longer than 30 characters.

**Comment by mmoayyed** [comment]
## This is an automated message. 

Thanks for the logging the issue report. Please investigate the problem, evaluate and analyze your logs at DEBUG level and whenever reasonable, file a pull request to address this case. 

Note: If you have already identified an enhancement or a bug fix, it is STRONGLY recommended that you simply submit a pull request to address the issue. There is no need for special ceremony to create separate issues.

The pull request IS the issue and it will be tracked and tagged as such. Do NOT log issues hoping for the problem to get resolved in the future by someone else. [Study the guide](CONTRIBUTING.md) and learn the skills to submit contributions, or reach out to a [commercial affiliate](https://www.apereo.org/content/commercial-affiliates) for assistance.

You can learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!

**Comment by jhitt25** [comment]
I would submit a pull, but this would require a column rename in the generated database.  Such a change would break existing installations on upgrade, so what is the protocol for denoting such a change?  Would implementing a flyway configuration be considered an acceptable solution, or is documenting the breaking change sufficient?

**Comment by mmoayyed** [comment]
Excellent. Let me help:

1. Could we simply consider this a non-issue by saying "Oracle prior to 12.2 isn't supported"? In which case, you'd simply make the breaking configuration change on your end in an overlay? I realize that is not ideal, but is it something we can own? Is supporting Oracle prior to 12.2 something significant?
2. In general, I do think flyway regardless of this bug is a very good thing to review and adjust. I personally would much rather things just work rather than documenting how to make them work, and if you're up to the task that would be superb. I've played around with it briefly, but if we can ideally integrate it with hibernate/DDL/etc to say: "if Oracle blah, then do it this way, otherwise that way" that would probably be the best option.

**Comment by jhitt25** [comment]
Not supporting Oracle prior to 12.2 is a bit extreme, considering 12.1 is under standard support for another year, and even 11.2 is under extended support until 2020.  Additionally, i've tested against MySQL today as well, and it suffers from a similar problem.  There is a variable named "key" in one of the entity classes, which is a reserved word in MySQL.
Ultimately, more robust names specified in the Column annotations would seem to be needed, but to be able to update these in official releases would require a method for upgrading either through a detection mechanism or via something such as flyway.
For now i'll probably just override in our build, but i'll ponder on a long-term solution that will work for the official releases as well.

**Comment by mmoayyed** [comment]
Thank you. Please keep this posted as you review and find solutions.

**Comment by jhitt25** [comment]
I've created a pull request that addresses the MySQL issue without any sort of breaking changes.  The Oracle 12.1 aspect of the problem requires a far more involved solution that may not be worth the effort, so i'm punting on that for now.

**Comment by mmoayyed** [comment]
Great. Thanks!
