### ISSUE TITLE
OIDC Delegation: client_name from redirect_uri ignored by Azure AD

### ISSUE THREAD

**Issue by ghenadiibatalski** [apereo/cas#2711]
Hello, i'm facing the problem described below while trying to delegate the Authentication to Azure AD OpenID Connect endpoint. The **client_name** query parameter seems to be erased from the redirect_uri and not accepted anymore. Possibly is the only allowed parameter **state**?

Regards, Gena

- CAS server version
5.1.0
- Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)  
Tomcat, Docker

- Steps to duplicate the problem along with your CAS settings and properties
Try to authenticate via configured Azure AD OpenID Connect endpoint
No reaction on back redirect because of missing **client_name** query parameter.
The generated url for accessing Azure is just fine and contains the correct client_name.

- Stacktraces
If adding the **client_name=AzureAdClient** by hand, the processing goes further (what is ok):
```bash
 org.pac4j.core.exception.TechnicalException: State parameter is different from the one sent in authentication request. Session expired or possible threat of cross-site request forgery
at org.pac4j.oidc.credentials.extractor.OidcExtractor.extract(OidcExtractor.java:80) ~[pac4j-oidc-2.0.0.jar!/:?]
at org.pac4j.oidc.credentials.extractor.OidcExtractor.extract(OidcExtractor.java:31) ~[pac4j-oidc-2.0.0.jar!/:?]
``` 

- Configuration/Overlay

 Configuration
```bash
cas.authn.pac4j.oidc[0].type=AZURE
cas.authn.pac4j.oidc[0].discoveryUri=https://login.microsoftonline.com/<tenant>/.well-known/openid-configuration
cas.authn.pac4j.oidc[0].scope=openid profile email groups
cas.authn.pac4j.oidc[0].id=<application id>
cas.authn.pac4j.oidc[0].secret=<some secret

#Pac4j Delegated AuthN
cas.authn.pac4j.typedIdUsed=true
cas.authn.pac4j.autoRedirect=false
```
  Overlay

```gradle
dependencies {
    compile "org.apereo.cas:cas-server-webapp-tomcat:${project.'cas.version'}@war"

    // Enable JSON config
    compile "org.apereo.cas:cas-server-support-json-service-registry:${project.'cas.version'}"

    // Enable OIDC delegation
    compile "org.apereo.cas:cas-server-support-pac4j-webflow:${project.'cas.version'}"
}
```

**Comment by mmoayyed** [comment]
## This is an automated message. 

Thanks for the logging the issue report. Please investigate the problem, evaluate and analyze your logs at DEBUG level and whenever reasonable, file a pull request to address this case. 

Note: If you have already identified an enhancement or a bug fix, it is STRONGLY recommended that you simply submit a pull request to address the issue. There is no need for special ceremony to create separate issues.

The pull request IS the issue and it will be tracked and tagged as such. Do NOT log issues hoping for the problem to get resolved in the future by someone else. [Study the guide](CONTRIBUTING.md) and learn the skills to submit contributions, or reach out to a [commercial affiliate](https://www.apereo.org/content/commercial-affiliates) for assistance.

You can learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!

**Comment by gbatalski** [comment]
please take a look to https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/TXDXd2pucv8

**Comment by mmoayyed** [comment]
Thanks for the proposal. Just a quick reminder that your message is probably better suited for the dev list. May I respond here, or would you rather continue on the list?

**Comment by gbatalski** [comment]
i think, it's better here.

**Comment by mmoayyed** [comment]
Excellent.

> Resolution for the 1. and 2. is to remove the client_name parameter form the callback url done for example via call to
> ```
> AzureAdClient.setIncludeClientNameInCallbackUrl(false);
> ```
> within the constructor of AzureAdClient.

I think this is just fine.

> This improvement works well excepting the circumstance, that the CAS server stopped to forward the callback redirects to the correct client. I assume, this occurs because of missing of client_name parameter. If i append the client_name=AzureADClient1 via url rewriting, the request is processed well, validation succeeds and the application (in my case it was CAS Management Webapp) is happy to login me.

We do need to verify this assumption, as I sadly myself do not remember where this requirement is enforced, if any. 

My proposal is to define a context path named "oidc" (or more convinient?) followed by the client_name for the callback url (eg. /oidc/AzureADClient1 etc. ). The filter for "/oidc/*" could than route the requests correctly to the right handler.


> It could be helpful to provide optional attributes for display label and description within the client configuration to customize client button/link.  If somebody has multiple realms/apps by the same provider, all of client buttons are labeled with the same "AzureAd", what is a little bit confusing.

I believe this may already be handled via a `name` property in the configuration. If you want to add a description to the client as well such that it can be displayed in the UI, that would be a change you first need to add to pac4j for relevant clients, and work with @leleuj . 


> how does the request routing implemented within the CAS

You'll have to explain what you mean by request routing. There are multiple avenues where this is done, and it is context specific. Some requests are handled by controllers that are routed to various flows and back.

> how one can define an additional context path for a service/delegate configuration

You can simply define a `@Controller` as a `@Bean` and have it be mapped to a particular GET/POST method of a some path you define. See examples in the codebase.

**Comment by gbatalski** [comment]
Ok, with the routing i meant the registration of the /oidc/ endpoint to be used instead of client_name parameter, if it's really needed. I'll take a look at ```@Controller``` usage . 

Could you please give me a hint which ```@Controller / @Bean/ filter``` handles the client_name param now?

**Comment by mmoayyed** [comment]
You want to look at DelegatedClientAuthenticationAction and Pac4jErrorViewResolver. Note that most if not all of your changes probably belong in pac4j, and not here.

**Comment by gbatalski** [comment]
@mmoayyed  Ok, thank you for the hints! I've taken a look at the implementation and want to hold some facts and ideas here:

1. `DelegatedClientAuthenticationAction` expects the `client_name` request parameter to route request to the right client. But such parameter is not present in the callback request anymore.  Only `code` and `state` are the allowed parameters, at least by Azure AD OIDC.
1.  The clients are enumerated and named within the `Pac4jAuthenticationEventExecutionPlanConfiguration.configureOidcClient`. If we assume (i'm absolutely not sure about this assumption), that the positioning withing the config file and the order in an iteration are stable, the clients will be named continuously eg. `AzureAdClient`, `AzureAdClient1`, `AzureAdClient2` etc. The numbering strategy becomes interesting for defining of the callback urls in a `pac4j` and especially for registering the allowed redirect urls within the authentication provider (eg. Azure or others).
1. The redirect url won't contain a `client_name` parameter. For establishing the request routing we also could/should define a delegation context path eg `/delegation/<clientName>` , something like `https://cas.mydomain.com/cas/delegation/AzureAdClient1` . The controller listening on such context path (`/delegation`?) extracts then the client name and delegates the processing of the request to `DelegatedClientAuthenticationAction` by adding the `clientName` parameter or via generalization of the delegation functionality for use it from new controller directly next to existing `DelegatedClientAuthenticationAction` (backward compatibility).
1. The solution could be generic for all delegation clients routed via `DelegatedClientAuthenticationAction` even we're facing the problem only with Azure OIDC.

I have also some questions about the implementation.
1. What is the simplest way to make `DelegatedClientAuthenticationAction` available also via some predefined context path?
1. What should be the name of this context path? (`/delegation` or something else?)
1. Where should the controller go, if such an extra controller serving this context path is really needed?
1. What is the better/preffered way to define the redirect url within `pac4j`?
1. Should i do the prototyping only for Azure OIDC clients?

Regards, Gena

**Comment by mmoayyed** [comment]
I think the overall theme of your approach is fine. Designating specific callback URLs for each client type seems like a better and more scalable approach that query parameters. 

Note that almost all of your changes belong in pac4j and not here. This is the sort of thing where pac4j should handle "automatically", which is why we use the library to begin with. Your 1-5 needs to exclusively go into pac4j, which then CAS becomes a user of. 

> What is the simplest way to make DelegatedClientAuthenticationAction available also via some predefined context path?

- You define a controller for the context path.
- You move the code inside the action into a reusable component/utility
- You call the utility code in both the controller and the action.

> What should be the name of this context path? (/delegation or something else?)

`delegatedAuthn` works for me.

> Where should the controller go, if such an extra controller serving this context path is really needed?

Inside pac4j. As I said, almost all of your changes MUST go inside pac4j. We do not want to have "custom" logic in CAS that knows how to deal with specific clients, etc. That's the job for pac4j, and all else is simply technical noise that the library should handle automatically.

> What is the better/preffered way to define the redirect url within pac4j?

That question is better answered by @leleuj 

> Should i do the prototyping only for Azure OIDC clients?

Yes! Though discuss with Jerome first. 

https://github.com/pac4j/pac4j/issues
http://www.pac4j.org/mailing-lists.html
