### ISSUE TITLE
Authentication failure specifying empty password for `default` bucket (Couchbase)

### ISSUE THREAD

**Issue by rdev5** [apereo/cas#2771]
Error at runtime:
````
2017-07-06 14:04:44,323 INFO [org.apereo.cas.ticket.registry.CouchbaseTicketRegistry] - <Setting up Couchbase Ticket Registry instance>
2017-07-06 14:04:44,857 WARN [com.couchbase.client.core.endpoint.Endpoint] - <[null][KeyValueEndpoint]: Authentication Failure.>
2017-07-06 14:04:44,886 WARN [com.couchbase.client.core.endpoint.Endpoint] - <[null][KeyValueEndpoint]: Authentication Failure.>
2017-07-06 14:04:44,886 WARN [com.couchbase.client.core.endpoint.Endpoint] - <Error during reconnect: >
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.checkIsAuthed(KeyValueAuthHandler.java:288) ~[core-io-1.3.7.jar!/:?]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:173) ~[core-io-1.3.7.jar!/:?]
        at com.couchbase.client.core.endpoint.kv.KeyValueAuthHandler.channelRead0(KeyValueAuthHandler.java:52) ~[core-io-1.3.7.jar!/:?]

...

2017-07-06 14:04:44,886 WARN [com.couchbase.client.core.endpoint.Endpoint] - <[null][KeyValueEndpoint]: Could not connect to endpoint, retrying with delay 32 MILLISECONDS: >
com.couchbase.client.core.endpoint.kv.AuthenticationException: Authentication Failure
````

This line ([CouchbaseClientFactory.java#L73](
https://github.com/apereo/cas/blob/5.1.x/support/cas-server-support-couchbase-core/src/main/java/org/apereo/cas/couchbase/core/CouchbaseClientFactory.java#L73)) may need to be refactored to use either of the default `openBucket` constructors which explicitly declare connectivity to the `default` with no password (timeout optional):

> `Bucket openBucket()` - Opens the default bucket with an empty password with the default connect timeout.
> `Bucket openBucket(long timeout, java.util.concurrent.TimeUnit timeUnit)` - Opens the default bucket with an empty password with a custom timeout.

Reference: http://docs.couchbase.com/sdk-api/couchbase-java-client-2.0.0/com/couchbase/client/java/Cluster.html

And yes, I know what you're going to say, "Please investigate and submit a pull request."

I'm going to try creating a different bucket first, one that is *not* **default** which [*does not* support passwords](https://developer.couchbase.com/documentation/server/current/security/security-bucket-protection.html) to begin with.

**Comment by mmoayyed** [comment]
> And yes, I know what you're going to say, "Please investigate and submit a pull request."

Great. Please do. 

> If you have already identified an enhancement or a bug fix, it is STRONGLY recommended that you simply submit a pull request to address the case. There is no need for special ceremony to create separate issues. The pull request IS the issue and it will be tracked and tagged as such. Do NOT log issues hoping for the issue to get resolved in the future by someone else. Study the guide and learn the skills to submit contributions, or reach out to a commercial affiliate for assistance.

**Comment by mmoayyed** [comment]
More guidelines in case it helps https://apereo.github.io/2017/07/05/cas-contribution-guide/
