### ISSUE TITLE
SAML2 Service Management

### ISSUE THREAD

**Issue by arbner** [apereo/cas#2873]
I was going to do something like https://github.com/apereo/cas/pull/2864 for the master branch, but noticed that the management webapp seems to have a few bugs in 5.2.0-RC2, and 5.2.0-RC3-SNAPSHOT currently does not run on my machine because of bean initialization errors:
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'grouperMultifactorAuthenticationConfiguration': Unsatisfied dependency expre
ssed through field 'centralAuthenticationService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.Centr
alAuthenticationService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(req
uired=true), @org.springframework.beans.factory.annotation.Qualifier(value=centralAuthenticationService)}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        ... 28 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.CentralAuthenticationService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=centralAuthenticationService)}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1493)

```
I'd just keep my hands off for now... but wanted to point it out.

**Comment by arbner** [comment]
update:
the last exception was with ldap service registry added to the build.
without it, I get the following:
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ticketRegistryCleaner' defined in class path resource [org/apereo/cas/config
/CasCoreTicketsSchedulingConfiguration.class]: Unsatisfied dependency expressed through method 'ticketRegistryCleaner' parameter 1; nested exception is org.springframework.beans.factor
y.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.logout.LogoutManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency
annotations: {@org.springframework.beans.factory.annotation.Qualifier(value=logoutManager)}
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        ...  more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.logout.LogoutManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value=logoutManager)}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1493)
        ...
```

**Comment by mmoayyed** [comment]
Thanks. Are you building from source or just using the sonatype snapshots? what commit id are you on and are you sure you are recent?

**Comment by mmoayyed** [comment]
Never mind. I see it. Good catch.

I should point out that the management app is being reworked and is getting a fairly new facelift altogether. It might be ready by RC3 for an initial merge.

**Comment by mmoayyed** [comment]
I have this fixed locally, but am not able to push at the moment. Please check back by tomorrow morning and we should be set to go.

**Comment by mmoayyed** [comment]
Fixed. You can resume if you want. Thanks!
