### ISSUE TITLE
SAML2 Metadata UI parsing exception

### ISSUE THREAD

**Issue by fmartelli** [apereo/cas#2880]
It seems there is a bug about Metadata UI info parsing.

Shortly, in SamlMetadataUIInfo, the methos getDisplayNames return a Collection of String by using getStringValues method explicitly.

Unfortunately, the method to retrieve the localized display name getDisplayName is leveraging on getLocalizedValues method which is expecting a list of LocalizedName objects (not strings).

Thus, the parsing is failing reporting the exception reported below.. 

- CAS server version 5.2.0-RC3-SNAPSHOT
- Container Tomcat on Linux
- Steps:
  configure SAML2 Authentication
  add metadata UI (mdui:UIInfo) into a SP metadata
  try out with a SP Initiated login

- The process ends on the authentication page with the following exception

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.opensaml.saml.saml2.metadata.LocalizedName
    at org.apereo.cas.support.saml.mdui.SamlMetadataUIInfo.getLocalizedValues(SamlMetadataUIInfo.java:240) ~[classes/:5.2.0-RC3-SNAPSHOT]
    at org.apereo.cas.support.saml.mdui.SamlMetadataUIInfo.getDisplayName(SamlMetadataUIInfo.java:164) ~[classes/:5.2.0-RC3-SNAPSHOT]
    at org.apereo.cas.support.saml.mdui.SamlMetadataUIInfo.getDisplayName(SamlMetadataUIInfo.java:170) ~[classes/:5.2.0-RC3-SNAPSHOT]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
    at org.springframework.expression.spel.support.ReflectivePropertyAccessor$OptimalPropertyAccessor.read(ReflectivePropertyAccessor.java:636) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:379) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:324) ~[spring-expression-4.3.10.RELEASE.jar:4.3.10.RELEASE]
    at org.thymeleaf.spring4.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:263) ~[thymeleaf-spring4-3.0.7.RELEASE.jar:3.0.7.RELEASE]

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
