### ISSUE TITLE
NPE in REST

### ISSUE THREAD

**Issue by fedon** [apereo/cas#2883]
If I call createServiceTicket (/v1/tickets/{tgtId:.+}) with invalid TGT it causes NPE.

ERROR [org.apereo.cas.support.rest.TicketsResource] -
java.lang.NullPointerException: null
at org.apereo.cas.authentication.DefaultAuthenticationResultBuilder.lambda$buildAuthenticationHistory$1(DefaultAuthenticationResultBuilder.java:118) ~[cas-server-core-authentication-5.1.4-SNAPSHOT.jar:5.1.4-SNAPSHOT]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_66]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_66]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_66]
at org.apereo.cas.authentication.DefaultAuthenticationResultBuilder.buildAuthenticationHistory(DefaultAuthenticationResultBuilder.java:117) ~[cas-server-core-authentication-5.1.4-SNAPSHOT.jar:5.1.4-SNAPSHOT]

**Comment by fedon** [comment]
But you closed my Pull Request without explanation!

**Comment by mmoayyed** [comment]
That's not quite true. Let me explain: I am not saying this issue is invalid or does not exist. I am simply saying your pull request is not the appropriate fix, and you need to dig deeper to find the root cause and prevent it there. That's the explanation.
