### ISSUE TITLE
cas properties about boot admin client can not work

### ISSUE THREAD

**Issue by Razor0719** [apereo/cas#2887]
this is the log： 
```
2017-08-28 06:02:01,982 ERROR [org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler] - <Unexpected error occurred in scheduled task.>
java.lang.IllegalStateException: serviceUrl must be set when deployed to servlet-container
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.getServiceUrl(DefaultApplicationFactory.java:61) ~[spring-boot-admin-starter-client-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.client.registration.DefaultApplicationFactory.createApplication(DefaultApplicationFactory.java:46) ~[spring-boot-admin-starter-client-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.createApplication(ApplicationRegistrator.java:126) ~[spring-boot-admin-starter-client-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.client.registration.ApplicationRegistrator.register(ApplicationRegistrator.java:65) ~[spring-boot-admin-starter-client-1.5.0.jar:1.5.0]
	at de.codecentric.boot.admin.client.registration.RegistrationApplicationListener$1.run(RegistrationApplicationListener.java:80) ~[spring-boot-admin-starter-client-1.5.0.jar:1.5.0]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_141]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

```

And this is the cas properties about boot admin：
```
 spring.boot.admin.url=https://ip:port/casbootadminserver
 spring.boot.admin.client.managementUrl=https://host:port/cas/status
 spring.boot.admin.client.name=Apereo CAS
 spring.boot.admin.client.metadata.user.name=admin
 spring.boot.admin.client.metadata.user.password=admin
```

I deploy the cas server and CAS Spring Boot Administration server by war in different Tomcat9 servers.Without the property of spring.boot.admin.url,cas server works successfully.

In addition,cas properties are all listed in `cas.properties` under the /etc/cas/config.

Thanks!

**Comment by mmoayyed** [comment]
You need to discuss this with the boot admin project.

**Comment by mmoayyed** [comment]
You can also take a look at the heroku-caswebapp to see a functional instance.

**Comment by mmoayyed** [comment]
Also, this is perhaps not relevant but remember that Tomcat 9 isn't officially supported.

**Comment by Razor0719** [comment]
@mmoayyed Thanks,I'll take a try!

**Comment by mmoayyed** [comment]
Excellent. If you find something that is peculiar from a CAS perspective please post back (though I very much doubt because there isn't much in CAS that would "configure" anything in this module).
