### ISSUE TITLE
cas-management cant not save service on v5.2.0-RC2

### ISSUE THREAD

**Issue by laomazi2006** [apereo/cas#2907]
https://github.com/apereo/cas/blob/3a967fff493f0fbdb10c3b564e0589bb003fdb0b/webapp-mgmt/cas-management-webapp/src/main/resources/static/js/app/app-angular.js#L1039

https://github.com/apereo/cas/blob/3a967fff493f0fbdb10c3b564e0589bb003fdb0b/webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/services/web/beans/RegisteredServiceAttributeReleasePolicyEditBean.java#L45

@mmoayyed 
 
```java
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of org.apereo.cas.mgmt.services.web.beans.RegisteredServiceAttributeReleasePolicyStrategyEditBean out of START_ARRAY token
 at [Source: (PushbackInputStream); line: 1, column: 1655] (through reference chain: org.apereo.cas.mgmt.services.web.beans.RegisteredServiceEditBean$ServiceData["attrRelease"]->org.apereo.cas.mgmt.services.web.beans.RegisteredServiceAttributeReleasePolicyEditBean["attrPolicy"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1329) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1439) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:185) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:368) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3072) ~[jackson-databind-2.9.0.jar!/:2.9.0]
        at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235) ~[spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
        ... 72 more
```

**Comment by mmoayyed** [comment]
This is being worked, under dev. Wait for RC3.

**Comment by mmoayyed** [comment]
Howdy, I recommend you give the existing snapshot a try for RC3 and post back if and when you find issues. This is a fairly significant change and your feedback is very much welcomed.

**Comment by laomazi2006** [comment]
Thank you. I've already tried RC3-SNAPSHOT, but somthing error. I try to add `cas-server-support-mongo-ticket-registry`、`cas-server-core-logout` and following error.

```java
2017-09-07 10:15:46,468 INFO [org.apereo.cas.mgmt.web.CasManagementWebApplication] - <The following profiles are active: dev>
2017-09-07 10:16:30,431 INFO [org.apereo.cas.services.ServiceRegistryInitializer] - <The service registry database will not be initialized from JSON services. If the service registry database ends up empty, CAS will refuse to authenticate services until service definitions are added to the registry. To auto-initialize the service registry, set 'cas.serviceRegistry.initFromJson=true' in your CAS settings.>
2017-09-07 10:16:33,893 INFO [org.apereo.cas.support.saml.OpenSamlConfigBean] - <Initialized OpenSaml successfully.>
2017-09-07 10:16:34,005 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casCoreLogoutConfiguration': Unsatisfied dependency expressed through field 'authenticationRequestServiceSelectionStrategies'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.authentication.AuthenticationServiceSelectionPlan' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=authenticationServiceSelectionPlan)}>
2017-09-07 10:16:39,044 ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] - <

***************************
APPLICATION FAILED TO START
***************************

Description:

Field authenticationRequestServiceSelectionStrategies in org.apereo.cas.logout.config.CasCoreLogoutConfiguration required a bean of type 'org.apereo.cas.authentication.AuthenticationServiceSelectionPlan' that could not be found.


Action:

Consider defining a bean of type 'org.apereo.cas.authentication.AuthenticationServiceSelectionPlan' in your configuration.
>
```

**Comment by mmoayyed** [comment]
remove them both and make sure you are running the latest commit.

**Comment by laomazi2006** [comment]
lates `cas-management-webapp-5.2.0-RC3-20170906.211804-81`,
CAS Commit Id: d33234e04fd63279ff4a864a934421f0407ae940
remove all is ok .After add  `cas-server-support-mongo-service-registry` then not working not working as expected.

```java
2017-09-07 15:31:15,545 INFO [org.apereo.cas.mgmt.web.CasManagementWebApplication] - <The following profiles are active: dev>
2017-09-07 15:32:04,524 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authenticationTransactionManager' defined in class path resource [org/apereo/cas/config/CasCoreAuthenticationConfiguration.class]: Unsatisfied dependency expressed through method 'authenticationTransactionManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casAuthenticationManager' defined in class path resource [org/apereo/cas/config/CasCoreAuthenticationConfiguration.class]: Unsatisfied dependency expressed through method 'casAuthenticationManager' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casCoreAuthenticationPolicyConfiguration': Unsatisfied dependency expressed through field 'ticketRegistry'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apereo.cas.ticket.registry.TicketRegistry' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=ticketRegistry)}>
2017-09-07 15:35:57,280 ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] - <

***************************
APPLICATION FAILED TO START
***************************

Description:

Field ticketRegistry in org.apereo.cas.config.CasCoreAuthenticationPolicyConfiguration required a bean of type 'org.apereo.cas.ticket.registry.TicketRegistry' that could not be found.




Action:

Consider defining a bean of type 'org.apereo.cas.ticket.registry.TicketRegistry' in your configuration.
```

```cas server have error on RC3-SNAPSHOT```

```java
2017-09-07 15:42:25,039 ERROR [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <org.apereo.cas.ticket.TicketGrantingTicketImpl>
java.lang.RuntimeException: org.apereo.cas.ticket.TicketGrantingTicketImpl
        at org.apereo.cas.ticket.BaseTicketSerializers.deserializeTicket(BaseTicketSerializers.java:148) ~[cas-server-core-tickets-5.2.0-RC3-SNAPSHOT.jar!/:5.2.0-RC3-SNAPSHOT]
        at org.apereo.cas.ticket.registry.MongoDbTicketRegistry.deserializeTicketFromMongoDocument(MongoDbTicketRegistry.java:231) ~[cas-server-support-mongo-ticket-registry-5.2.0-RC3-SNAPSHOT.jar!/:5.2.0-RC3-SNAPSHOT]
        at org.apereo.cas.ticket.registry.MongoDbTicketRegistry.lambda$getTickets$2(MongoDbTicketRegistry.java:172) ~[cas-server-support-mongo-ticket-registry-5.2.0-RC3-SNAPSHOT.jar!/:5.2.0-RC3-SNAPSHOT]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_91]
```

**Comment by mmoayyed** [comment]
Ah, excellent. Thanks for checking. This must be fixed.

**Comment by mmoayyed** [comment]
Fixed via https://github.com/apereo/cas/commit/c49a07ce1f0e4e253dce53fa869a5ff7fd70d645 and family.

**Comment by laomazi2006** [comment]
ha ha, Looking forward to the 5.2.0 release.
