### ISSUE TITLE
Load shiro.ini error on v5.1.3

### ISSUE THREAD

**Issue by laomazi2006** [apereo/cas#2929]
**5.1.3**

Shiro Authentication set `cas.authn.shiro.config.location=classpath:shiro.ini` ,run after,some error

I saw cas to load shiro.ini from the system temp dir but not exists and then thows exceptions

**Comment by mmoayyed** [comment]
Please review the issue template to understand the guidelines before submitting issues. The report here simply does not contain enough data for it to merit any further diagnostics. The issue template presents itself when you begin to submit a new issue. It is also [available here](https://github.com/apereo/cas/blob/master/ISSUE_TEMPLATE.md).

Additional guidelines can be found [here](https://apereo.github.io/cas/Mailing-Lists.html#data-data-data).

**Comment by laomazi2006** [comment]
Thank you, I will.
First, add `cas-server-support-generic` dependency in the pom.xml,   add a line `cas.authn.shiro.config.location=classpath:shiro.ini` in the application.paoperties, add file `shiro.ini` to resources directory ,next I run the cas-server, that'is ok. But I find shiro.ini the same as project resources in my system of temporary directory.
After delete  the shiro.ini in my system of temporary directory and rerun.

I try again and again.
Debug:
https://github.com/apereo/cas/blob/b6cfef38b6615aa1ceee3f0956083c42e01b8a34/support/cas-server-support-generic/src/main/java/org/apereo/cas/adaptors/generic/config/ShiroAuthenticationEventExecutionPlanConfiguration.java#L65
Next to execute `loadShiroConfiguration`
Expression `shiro.getConfig().getLocation().exists()` is true.The description is illustrated in classpath.


https://github.com/apereo/cas/blob/b6cfef38b6615aa1ceee3f0956083c42e01b8a34/core/cas-server-core-util/src/main/java/org/apereo/cas/util/ResourceUtils.java#L162

I don't know when cas created  cas directory for me on the temporary directory.

Is there something wrong with my configuration?

Thanks again.


```cmd
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.shiroAuthenticationHandler' defined in class path resource [org/apereo/cas/adaptors/generic/config/ShiroAuthenticati
onEventExecutionPlanConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.authentication.Authenticatio
nHandler]: Factory method 'shiroAuthenticationHandler' threw exception; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\ADMINI~1\AppData\Local\Temp\cas\shiro.ini (系统找不到指定的路径。)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:345)
        at org.springframework.cloud.context.scope.GenericScope$BeanLifecycleWrapper.getBean(GenericScope.java:359)
        at org.springframework.cloud.context.scope.GenericScope.get(GenericScope.java:176)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:192)
        at com.sun.proxy.$Proxy118.getName(Unknown Source)
        at org.apereo.cas.authentication.DefaultAuthenticationEventExecutionPlan.registerAuthenticationHandlerWithPrincipalResolver(DefaultAuthenticationEventExecutionPlan.java:40)
```

**Comment by laomazi2006** [comment]
@mmoayyed 5.2.0-RC3 MongoDb Events Document is `cas.events.mongodb` I saw is `cas.events.mongo`, Right?

https://apereo.github.io/cas/development/installation/Configuration-Properties.html#mongodb-events

**Comment by mmoayyed** [comment]
I'd recommend that you move away from classpath-based configuration and define the file under /etc/cas or some such path.
