### ISSUE TITLE
Pb with DefaultCassandraRepository (cas-server-support-cassandra-authentication) in version 5.2.0-RC3

### ISSUE THREAD

**Issue by NicoMabriez** [apereo/cas#2966]
Hello,

I'm still testing the cassandra authentication module in version 5.2.0-RC3 and I get a new error when trying to authenticate.
Here are the info:

CAS server version : 5.2.0-RC3
Container/environment type/version: Tomcat / Linux
Steps to duplicate the problem along with your CAS settings and properties:
Just add the dependency cas-server-support-cassandra-authentication in the pom.xml

Stacktraces and CAS DEBUG logs where appropriate:
```
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name cassandra
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:104)
	at org.apereo.cas.authentication.DefaultCassandraRepository.<init>(DefaultCassandraRepository.java:35)
	at org.apereo.cas.config.CassandraAuthenticationConfiguration.cassandraRepository(CassandraAuthenticationConfiguration.java:60)
	at org.apereo.cas.config.CassandraAuthenticationConfiguration$$EnhancerBySpringCGLIB$$bea0ae6e.CGLIB$cassandraRepository$1(<generated>)
	at org.apereo.cas.config.CassandraAuthenticationConfiguration$$EnhancerBySpringCGLIB$$bea0ae6e$$FastClassBySpringCGLIB$$a79309d3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at org.apereo.cas.config.CassandraAuthenticationConfiguration$$EnhancerBySpringCGLIB$$bea0ae6e.cassandraRepository(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 41 more
```

SOLUTION:
In DefaultCassandraRepository line 32, I think it should be 
`cassandraProperties.getUsernameAttribute());`
instead of
`cassandraProperties.getUsername());`

**Comment by mmoayyed** [comment]
Thanks! Good catch. You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
