### ISSUE TITLE
SamlRegisteredService_AttributeNameFormats - Error creating table

### ISSUE THREAD

**Issue by smallela1** [apereo/cas#2974]
Getting this error for cas 5.1  when the database is initialized. (Cas service management webapp)

```
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'varchar(255) not null, primary key (SamlRegisteredService_id, key)) engine=InnoD' at line 1
Query is : create table SamlRegisteredService_AttributeNameFormats (SamlRegisteredService_id bigint not null, value varchar(255), key varchar(255) not null, primary key (SamlRegisteredService_id, key)) engine=InnoDB
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125) ~[mariadb-java-client-1.4.6.jar:?]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[mariadb-java-client-1.4.6.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:242) ~[mariadb-java-client-1.4.6.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:270) ~[mariadb-java-client-1.4.6.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:283) ~[mariadb-java-client-1.4.6.jar:?]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:92) ~[HikariCP-2.6.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-2.6.1.jar:?]
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54) ~[hibernate-core-5.2.10.Final.jar:5.2.10.Final]
```

**Comment by mmoayyed** [comment]
Your database is not initialized or created correctly .Either create the schema yourself or let CAS do it.
