### ISSUE TITLE
cas-management-webapp overlay fail

### ISSUE THREAD

**Issue by laomazi2006** [apereo/cas#3007]
Hi~

When I Upgrade from version `5.2.0-RC3` to version `5.2.0-RC4`, `cas-server-webapp-tomcat` is working well, but `cas-management-webapp` something error from package.

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
        <groupId>com.sunrizetech</groupId>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>auth-services-management</artifactId>
    <packaging>war</packaging>

    <properties>
        <cas.version>5.2.0-RC4</cas.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>com.rimerosolutions.maven.plugins</groupId>
                <artifactId>wrapper-maven-plugin</artifactId>
                <version>0.0.5</version>
                <configuration>
                    <verifyDownload>true</verifyDownload>
                    <checksumAlgorithm>MD5</checksumAlgorithm>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <warName>cas-management</warName>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <recompressZippedFiles>false</recompressZippedFiles>
                    <archive>
                        <compress>false</compress>
                        <manifestFile>${project.build.directory}/war/work/org.apereo.cas/cas-management-webapp/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                    <overlays>
                        <overlay>
                            <groupId>org.apereo.cas</groupId>
                            <artifactId>cas-management-webapp</artifactId>
                            <excludes>
                                <exclude>WEB-INF/classes/services/*</exclude>
                                <exclude>WEB-INF/classes/application.*</exclude>
                                <exclude>WEB-INF/classes/bootstrap.properties</exclude>
                                <exclude>**/messages_*.properties</exclude>
                                <exclude>**/truststore.jks</exclude>
                                <exclude>**/user-details.properties</exclude>
                            </excludes>
                        </overlay>
                    </overlays>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
            </plugin>
        </plugins>
        <finalName>cas-management</finalName>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apereo.cas</groupId>
            <artifactId>cas-server-support-mongo-service-registry</artifactId>
            <version>${cas.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apereo.cas</groupId>
            <artifactId>cas-management-webapp</artifactId>
            <version>${cas.version}</version>
            <type>war</type>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
</project>
```

run, build.cmd package or build.cmd run
```cmd
mvn package -e -X
```
And I try again and again `build.cmd clean`, `build.cmd` some error like that...，but **RC3** is ok.

error:

```cmd
[DEBUG]  + WEB-INF/lib/metrics-json-3.2.5.jar has been copied.
[DEBUG] Processing: profiler-1.0.2.jar
[DEBUG]  + WEB-INF/lib/profiler-1.0.2.jar has been copied.
[DEBUG] Processing: metrics-spring-3.1.3.jar
[DEBUG]  + WEB-INF/lib/metrics-spring-3.1.3.jar has been copied.
[DEBUG] Processing: cas-management-webapp-5.2.0-RC4.war
[DEBUG] war artifacts are handled as overlays, ignoring [org.apereo.cas:cas-management-webapp:war:5.2.0-RC4:runtime]
[DEBUG] Processing: spring-boot-admin-starter-client-1.5.4.jar
[DEBUG]  + WEB-INF/lib/spring-boot-admin-starter-client-1.5.4.jar has been copied.
[DEBUG] Processing: jolokia-core-1.3.7.jar
[DEBUG]  + WEB-INF/lib/jolokia-core-1.3.7.jar has been copied.
[DEBUG] Processing: json-simple-1.1.1.jar
[DEBUG]  + WEB-INF/lib/json-simple-1.1.1.jar has been copied.
[DEBUG] Processing: junit-4.10.jar
[DEBUG]  + WEB-INF/lib/junit-4.10.jar has been copied.
[DEBUG] Processing: hamcrest-core-1.1.jar
[DEBUG]  + WEB-INF/lib/hamcrest-core-1.1.jar has been copied.
[DEBUG] OverlayPackagingTask performPackaging overlay.getTargetPath() null
[INFO] Processing overlay [ id org.apereo.cas:cas-management-webapp]
[DEBUG] Expanding: D:\carl\soft\java\apache-maven-3.1.1\repository\org\apereo\cas\cas-management-webapp\5.2.0-RC4\cas-management-webapp-5.2.0-RC4.war into C:\carl\coder\workspace\sunrise\ESALEB-V3\AuthCenter\Source\Server\auth-services-management\target\war\work\org.apereo.cas\cas-management-webapp
[DEBUG] expand complete
[INFO] Webapp assembled in [1498 msecs]
[DEBUG] Excluding [] from the generated webapp archive.
[DEBUG] Including [**] in the generated webapp archive.
[DEBUG] Build won't fail if web.xml file is missing.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.669 s
[INFO] Finished at: 2017-10-17T15:23:10+08:00
[INFO] Final Memory: 34M/395M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.1.0:war (default-war) on project auth-services-management: Error assembling WAR: Manifest file: C:\carl\coder\workspace\auth-services-management\target\war\work\org.apereo.cas\cas-management-webapp\META-INF\MANIFEST.MF does not exist. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.1.0:war (default-war) on project auth-services-management: Error assembling WAR: Manifest file: C:\carl\coder\workspace\auth-services-management\target\war\work\org.apereo.cas\cas-management-webapp\META-INF\MANIFEST.MF does not exist.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error assembling WAR: Manifest file: C:\carl\coder\workspace\auth-services-management\target\war\work\org.apereo.cas\cas-management-webapp\META-INF\MANIFEST.MF does not exist.
        at org.apache.maven.plugins.war.WarMojo.execute(WarMojo.java:213)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: Manifest file: C:\carl\coder\workspace\auth-services-management\target\war\work\org.apereo.cas\cas-management-webapp\META-INF\MANIFEST.MF does not exist.
        at org.codehaus.plexus.archiver.jar.JarArchiver.setManifest(JarArchiver.java:218)
        at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:613)
        at org.apache.maven.plugins.war.WarMojo.performPackaging(WarMojo.java:268)
        at org.apache.maven.plugins.war.WarMojo.execute(WarMojo.java:197)
        ... 22 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Next I try to copy `cas-management-webapp-5.2.0-RC4.war` content to `auth-services-management/target/war/work/org.apereo.cas/cas-management-webapp` and run `mvn package` is working. `java -jar cas-management.war` is successful.

---
Configured wrong or something else?

Thanks.

**Comment by mmoayyed** [comment]
Your overlay is incorrect; it doesn't match the structure required for the management webapp yet. Once the overlays are switched, please pull from the overlay project and try again.

**Comment by mmoayyed** [comment]
I have on my todo list for the day to get the overlays updated before the final 5.2 release. Stay tuned.

**Comment by laomazi2006** [comment]
@mmoayyed Aha, thank you very much.

**Comment by laomazi2006** [comment]
I try.
clone from https://github.com/apereo/cas-services-management-overlay, and modify to `<cas.version>5.2.0-RC4</cas.version>`

The original(5.1.5) is OK.

```cmd
[INFO] --- maven-war-plugin:2.6:war (default-war) @ cas-overlay ---
[INFO] Packaging webapp
[INFO] Assembling webapp [cas-overlay] in [C:\carl\coder\workspace\personal\cas-services-management-overlay\target\cas-management]
[info] Copying manifest...
[INFO] Processing war project
[INFO] Processing overlay [ id org.apereo.cas:cas-management-webapp]
[INFO] Webapp assembled in [64 msecs]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.858 s (Wall Clock)
[INFO] Finished at: 2017-10-17T16:38:28+08:00
[INFO] Final Memory: 13M/210M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.6:war (default-war) on project cas-overlay: Error assembling WAR: Manifest file: C:\carl\coder\workspace\personal\cas-services-management-overlay\target\
war\work\org.apereo.cas\cas-management-webapp\META-INF\MANIFEST.MF does not exist. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

Just like the mistake above.

**Comment by mmoayyed** [comment]
You'll need to wait for a few hours until I get this done. Not all of the overlays are not yet ready for 5.2 and the pom.xml requires a few structural changes. I'll post something to the lists once this is done.

**Comment by mmoayyed** [comment]
Also noticed an issue with the management webapp and how it's built and released with CAS. Fix is pushed. Your overlay, once and when it's ready, will need to be based on 5.2.0-SNAPSHOT. (Which the overlay will use by default) in order to get the fix.

**Comment by laomazi2006** [comment]
OK, I will try. 
thank you
