### ISSUE TITLE
Meet "Failed to connect to Couchbase getBucket" exception from CouchbaseClientFactory when service starts up

### ISSUE THREAD

**Issue by ryzuo** [apereo/cas#3031]
Hi dear all,

This is my first time to use CAS, so the problem I've met may be a configuration issue, or it might be a known issue to you, although I tried things to understand it, I failed and cannot solve this.
I have built the CAS from WAR overlay template, and deployed it on one of my AWS host, and I have my Couchbase running on another AWS host, in the same group. I'm confident confirmed that everything relates to my Couchbase buckets access is correct(There are also some other my systems running on accessing it.) . And everything was okay when I tested the CAS and Couchbase on a same physical machine. However, after I moved the CAS to my AWS box, and configured it to connect to the Couchbase on AWS, when I tried to start my CAS with tomcat, I saw the "Failed to connect to Couchbase getBucket" exception in the log, the back trace was like below, it's too long and it's not the entire stack:
 
>>>>>>>>>>>>>>>>>>>>>>
2017-10-27 09:55:48,949 ERROR [org.apereo.cas.services.CouchbaseServiceRegistryDao] - <Failed to connect to Couchbase getBucket>
java.lang.IllegalArgumentException: Failed to connect to Couchbase getBucket
        at org.apereo.cas.couchbase.core.CouchbaseClientFactory.getBucket(CouchbaseClientFactory.java:137) ~[cas-server-support-couchbase-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
        at org.apereo.cas.couchbase.core.CouchbaseClientFactory$$FastClassBySpringCGLIB$$4ed9b429.invoke(<generated>) ~[cas-server-support-couchbase-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.cloud.context.config.StandardBeanLifecycleDecorator$2.invoke(StandardBeanLifecycleDecorator.java:85) ~[spring-cloud-context-1.2.4.RELEASE.jar:1.2.4.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.apereo.cas.couchbase.core.CouchbaseClientFactory$$EnhancerBySpringCGLIB$$a786e45f.getBucket(<generated>) ~[cas-server-support-couchbase-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
        at org.apereo.cas.couchbase.core.CouchbaseClientFactory$$FastClassBySpringCGLIB$$4ed9b429.invoke(<generated>) ~[cas-server-support-couchbase-core-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.12.RELEASE.jar:4.3.12.RELEASE]

<<<<<<<<<<<<<<<<<<<<
Certainly the web page is not accessible, but I saw there was a record written into my bucket already, which is for Service Registry to use that I configured. So this is strange to me, for the record can be created in the bucket, then what does this "Failed to connect to getBucket" mean. I took a look of the code in the CouchbaseClientFactory.java(did not went through the whole logic), it just simply catches a general Exception, not a specific exception. So which line of the codes might throw such a exception?

**Comment by mmoayyed** [comment]
Hello! Welcome to the project..

For support and questions, please join the relevant project mailing lists, chatroom or other support channels to ask questions.
